// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: billing/grpc/v1/private.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrystalPackage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Crystals        int32                  `protobuf:"varint,3,opt,name=crystals,proto3" json:"crystals,omitempty"`
	PriceMinorUnits int64                  `protobuf:"varint,4,opt,name=price_minor_units,json=priceMinorUnits,proto3" json:"price_minor_units,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsActive        bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CrystalPackage) Reset() {
	*x = CrystalPackage{}
	mi := &file_billing_grpc_v1_private_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrystalPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrystalPackage) ProtoMessage() {}

func (x *CrystalPackage) ProtoReflect() protoreflect.Message {
	mi := &file_billing_grpc_v1_private_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrystalPackage.ProtoReflect.Descriptor instead.
func (*CrystalPackage) Descriptor() ([]byte, []int) {
	return file_billing_grpc_v1_private_proto_rawDescGZIP(), []int{0}
}

func (x *CrystalPackage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CrystalPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CrystalPackage) GetCrystals() int32 {
	if x != nil {
		return x.Crystals
	}
	return 0
}

func (x *CrystalPackage) GetPriceMinorUnits() int64 {
	if x != nil {
		return x.PriceMinorUnits
	}
	return 0
}

func (x *CrystalPackage) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CrystalPackage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CrystalPackage) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListCrystalPackagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCrystalPackagesRequest) Reset() {
	*x = ListCrystalPackagesRequest{}
	mi := &file_billing_grpc_v1_private_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCrystalPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCrystalPackagesRequest) ProtoMessage() {}

func (x *ListCrystalPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_grpc_v1_private_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCrystalPackagesRequest.ProtoReflect.Descriptor instead.
func (*ListCrystalPackagesRequest) Descriptor() ([]byte, []int) {
	return file_billing_grpc_v1_private_proto_rawDescGZIP(), []int{1}
}

type ListCrystalPackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*CrystalPackage      `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCrystalPackagesResponse) Reset() {
	*x = ListCrystalPackagesResponse{}
	mi := &file_billing_grpc_v1_private_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCrystalPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCrystalPackagesResponse) ProtoMessage() {}

func (x *ListCrystalPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_grpc_v1_private_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCrystalPackagesResponse.ProtoReflect.Descriptor instead.
func (*ListCrystalPackagesResponse) Descriptor() ([]byte, []int) {
	return file_billing_grpc_v1_private_proto_rawDescGZIP(), []int{2}
}

func (x *ListCrystalPackagesResponse) GetPackages() []*CrystalPackage {
	if x != nil {
		return x.Packages
	}
	return nil
}

type GetCrystalPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCrystalPackageRequest) Reset() {
	*x = GetCrystalPackageRequest{}
	mi := &file_billing_grpc_v1_private_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCrystalPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrystalPackageRequest) ProtoMessage() {}

func (x *GetCrystalPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_grpc_v1_private_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrystalPackageRequest.ProtoReflect.Descriptor instead.
func (*GetCrystalPackageRequest) Descriptor() ([]byte, []int) {
	return file_billing_grpc_v1_private_proto_rawDescGZIP(), []int{3}
}

func (x *GetCrystalPackageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCrystalPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       *CrystalPackage        `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCrystalPackageResponse) Reset() {
	*x = GetCrystalPackageResponse{}
	mi := &file_billing_grpc_v1_private_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCrystalPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrystalPackageResponse) ProtoMessage() {}

func (x *GetCrystalPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_grpc_v1_private_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrystalPackageResponse.ProtoReflect.Descriptor instead.
func (*GetCrystalPackageResponse) Descriptor() ([]byte, []int) {
	return file_billing_grpc_v1_private_proto_rawDescGZIP(), []int{4}
}

func (x *GetCrystalPackageResponse) GetPackage() *CrystalPackage {
	if x != nil {
		return x.Package
	}
	return nil
}

type CreateCrystalPackageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Crystals        int32                  `protobuf:"varint,2,opt,name=crystals,proto3" json:"crystals,omitempty"`
	PriceMinorUnits int64                  `protobuf:"varint,3,opt,name=price_minor_units,json=priceMinorUnits,proto3" json:"price_minor_units,omitempty"`
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsActive        bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCrystalPackageRequest) Reset() {
	*x = CreateCrystalPackageRequest{}
	mi := &file_billing_grpc_v1_private_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCrystalPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCrystalPackageRequest) ProtoMessage() {}

func (x *CreateCrystalPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_grpc_v1_private_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCrystalPackageRequest.ProtoReflect.Descriptor instead.
func (*CreateCrystalPackageRequest) Descriptor() ([]byte, []int) {
	return file_billing_grpc_v1_private_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCrystalPackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCrystalPackageRequest) GetCrystals() int32 {
	if x != nil {
		return x.Crystals
	}
	return 0
}

func (x *CreateCrystalPackageRequest) GetPriceMinorUnits() int64 {
	if x != nil {
		return x.PriceMinorUnits
	}
	return 0
}

func (x *CreateCrystalPackageRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateCrystalPackageRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateCrystalPackageRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateCrystalPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       *CrystalPackage        `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCrystalPackageResponse) Reset() {
	*x = CreateCrystalPackageResponse{}
	mi := &file_billing_grpc_v1_private_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCrystalPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCrystalPackageResponse) ProtoMessage() {}

func (x *CreateCrystalPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_grpc_v1_private_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCrystalPackageResponse.ProtoReflect.Descriptor instead.
func (*CreateCrystalPackageResponse) Descriptor() ([]byte, []int) {
	return file_billing_grpc_v1_private_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCrystalPackageResponse) GetPackage() *CrystalPackage {
	if x != nil {
		return x.Package
	}
	return nil
}

type UpdateCrystalPackageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Crystals        int32                  `protobuf:"varint,3,opt,name=crystals,proto3" json:"crystals,omitempty"`
	PriceMinorUnits int64                  `protobuf:"varint,4,opt,name=price_minor_units,json=priceMinorUnits,proto3" json:"price_minor_units,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsActive        bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateCrystalPackageRequest) Reset() {
	*x = UpdateCrystalPackageRequest{}
	mi := &file_billing_grpc_v1_private_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCrystalPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCrystalPackageRequest) ProtoMessage() {}

func (x *UpdateCrystalPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_grpc_v1_private_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCrystalPackageRequest.ProtoReflect.Descriptor instead.
func (*UpdateCrystalPackageRequest) Descriptor() ([]byte, []int) {
	return file_billing_grpc_v1_private_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCrystalPackageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCrystalPackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCrystalPackageRequest) GetCrystals() int32 {
	if x != nil {
		return x.Crystals
	}
	return 0
}

func (x *UpdateCrystalPackageRequest) GetPriceMinorUnits() int64 {
	if x != nil {
		return x.PriceMinorUnits
	}
	return 0
}

func (x *UpdateCrystalPackageRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateCrystalPackageRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateCrystalPackageRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateCrystalPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       *CrystalPackage        `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCrystalPackageResponse) Reset() {
	*x = UpdateCrystalPackageResponse{}
	mi := &file_billing_grpc_v1_private_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCrystalPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCrystalPackageResponse) ProtoMessage() {}

func (x *UpdateCrystalPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_grpc_v1_private_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCrystalPackageResponse.ProtoReflect.Descriptor instead.
func (*UpdateCrystalPackageResponse) Descriptor() ([]byte, []int) {
	return file_billing_grpc_v1_private_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCrystalPackageResponse) GetPackage() *CrystalPackage {
	if x != nil {
		return x.Package
	}
	return nil
}

var File_billing_grpc_v1_private_proto protoreflect.FileDescriptor

const file_billing_grpc_v1_private_proto_rawDesc = "" +
	"\n" +
	"\x1dbilling/grpc/v1/private.proto\x12\x0fbilling.grpc.v1\"\xd2\x01\n" +
	"\x0eCrystalPackage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcrystals\x18\x03 \x01(\x05R\bcrystals\x12*\n" +
	"\x11price_minor_units\x18\x04 \x01(\x03R\x0fpriceMinorUnits\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"\x1c\n" +
	"\x1aListCrystalPackagesRequest\"Z\n" +
	"\x1bListCrystalPackagesResponse\x12;\n" +
	"\bpackages\x18\x01 \x03(\v2\x1f.billing.grpc.v1.CrystalPackageR\bpackages\"*\n" +
	"\x18GetCrystalPackageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x19GetCrystalPackageResponse\x129\n" +
	"\apackage\x18\x01 \x01(\v2\x1f.billing.grpc.v1.CrystalPackageR\apackage\"\xcf\x01\n" +
	"\x1bCreateCrystalPackageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcrystals\x18\x02 \x01(\x05R\bcrystals\x12*\n" +
	"\x11price_minor_units\x18\x03 \x01(\x03R\x0fpriceMinorUnits\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"Y\n" +
	"\x1cCreateCrystalPackageResponse\x129\n" +
	"\apackage\x18\x01 \x01(\v2\x1f.billing.grpc.v1.CrystalPackageR\apackage\"\xdf\x01\n" +
	"\x1bUpdateCrystalPackageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcrystals\x18\x03 \x01(\x05R\bcrystals\x12*\n" +
	"\x11price_minor_units\x18\x04 \x01(\x03R\x0fpriceMinorUnits\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"Y\n" +
	"\x1cUpdateCrystalPackageResponse\x129\n" +
	"\apackage\x18\x01 \x01(\v2\x1f.billing.grpc.v1.CrystalPackageR\apackage2\xdf\x03\n" +
	"\x15CrystalPackageService\x12p\n" +
	"\x13ListCrystalPackages\x12+.billing.grpc.v1.ListCrystalPackagesRequest\x1a,.billing.grpc.v1.ListCrystalPackagesResponse\x12j\n" +
	"\x11GetCrystalPackage\x12).billing.grpc.v1.GetCrystalPackageRequest\x1a*.billing.grpc.v1.GetCrystalPackageResponse\x12s\n" +
	"\x14CreateCrystalPackage\x12,.billing.grpc.v1.CreateCrystalPackageRequest\x1a-.billing.grpc.v1.CreateCrystalPackageResponse\x12s\n" +
	"\x14UpdateCrystalPackage\x12,.billing.grpc.v1.UpdateCrystalPackageRequest\x1a-.billing.grpc.v1.UpdateCrystalPackageResponseBQZOgithub.com/artcodefun/heat-expansion-server/contracts/billing/grpc/v1;billingv1b\x06proto3"

var (
	file_billing_grpc_v1_private_proto_rawDescOnce sync.Once
	file_billing_grpc_v1_private_proto_rawDescData []byte
)

func file_billing_grpc_v1_private_proto_rawDescGZIP() []byte {
	file_billing_grpc_v1_private_proto_rawDescOnce.Do(func() {
		file_billing_grpc_v1_private_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_grpc_v1_private_proto_rawDesc), len(file_billing_grpc_v1_private_proto_rawDesc)))
	})
	return file_billing_grpc_v1_private_proto_rawDescData
}

var file_billing_grpc_v1_private_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_billing_grpc_v1_private_proto_goTypes = []any{
	(*CrystalPackage)(nil),               // 0: billing.grpc.v1.CrystalPackage
	(*ListCrystalPackagesRequest)(nil),   // 1: billing.grpc.v1.ListCrystalPackagesRequest
	(*ListCrystalPackagesResponse)(nil),  // 2: billing.grpc.v1.ListCrystalPackagesResponse
	(*GetCrystalPackageRequest)(nil),     // 3: billing.grpc.v1.GetCrystalPackageRequest
	(*GetCrystalPackageResponse)(nil),    // 4: billing.grpc.v1.GetCrystalPackageResponse
	(*CreateCrystalPackageRequest)(nil),  // 5: billing.grpc.v1.CreateCrystalPackageRequest
	(*CreateCrystalPackageResponse)(nil), // 6: billing.grpc.v1.CreateCrystalPackageResponse
	(*UpdateCrystalPackageRequest)(nil),  // 7: billing.grpc.v1.UpdateCrystalPackageRequest
	(*UpdateCrystalPackageResponse)(nil), // 8: billing.grpc.v1.UpdateCrystalPackageResponse
}
var file_billing_grpc_v1_private_proto_depIdxs = []int32{
	0, // 0: billing.grpc.v1.ListCrystalPackagesResponse.packages:type_name -> billing.grpc.v1.CrystalPackage
	0, // 1: billing.grpc.v1.GetCrystalPackageResponse.package:type_name -> billing.grpc.v1.CrystalPackage
	0, // 2: billing.grpc.v1.CreateCrystalPackageResponse.package:type_name -> billing.grpc.v1.CrystalPackage
	0, // 3: billing.grpc.v1.UpdateCrystalPackageResponse.package:type_name -> billing.grpc.v1.CrystalPackage
	1, // 4: billing.grpc.v1.CrystalPackageService.ListCrystalPackages:input_type -> billing.grpc.v1.ListCrystalPackagesRequest
	3, // 5: billing.grpc.v1.CrystalPackageService.GetCrystalPackage:input_type -> billing.grpc.v1.GetCrystalPackageRequest
	5, // 6: billing.grpc.v1.CrystalPackageService.CreateCrystalPackage:input_type -> billing.grpc.v1.CreateCrystalPackageRequest
	7, // 7: billing.grpc.v1.CrystalPackageService.UpdateCrystalPackage:input_type -> billing.grpc.v1.UpdateCrystalPackageRequest
	2, // 8: billing.grpc.v1.CrystalPackageService.ListCrystalPackages:output_type -> billing.grpc.v1.ListCrystalPackagesResponse
	4, // 9: billing.grpc.v1.CrystalPackageService.GetCrystalPackage:output_type -> billing.grpc.v1.GetCrystalPackageResponse
	6, // 10: billing.grpc.v1.CrystalPackageService.CreateCrystalPackage:output_type -> billing.grpc.v1.CreateCrystalPackageResponse
	8, // 11: billing.grpc.v1.CrystalPackageService.UpdateCrystalPackage:output_type -> billing.grpc.v1.UpdateCrystalPackageResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_billing_grpc_v1_private_proto_init() }
func file_billing_grpc_v1_private_proto_init() {
	if File_billing_grpc_v1_private_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_grpc_v1_private_proto_rawDesc), len(file_billing_grpc_v1_private_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_grpc_v1_private_proto_goTypes,
		DependencyIndexes: file_billing_grpc_v1_private_proto_depIdxs,
		MessageInfos:      file_billing_grpc_v1_private_proto_msgTypes,
	}.Build()
	File_billing_grpc_v1_private_proto = out.File
	file_billing_grpc_v1_private_proto_goTypes = nil
	file_billing_grpc_v1_private_proto_depIdxs = nil
}
