// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: billing/grpc/v1/private.proto

package billingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrystalPackageService_ListCrystalPackages_FullMethodName  = "/billing.grpc.v1.CrystalPackageService/ListCrystalPackages"
	CrystalPackageService_GetCrystalPackage_FullMethodName    = "/billing.grpc.v1.CrystalPackageService/GetCrystalPackage"
	CrystalPackageService_CreateCrystalPackage_FullMethodName = "/billing.grpc.v1.CrystalPackageService/CreateCrystalPackage"
	CrystalPackageService_UpdateCrystalPackage_FullMethodName = "/billing.grpc.v1.CrystalPackageService/UpdateCrystalPackage"
)

// CrystalPackageServiceClient is the client API for CrystalPackageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CrystalPackageService exposes admin CRUD operations for crystal packages.
// All RPCs require the x-internal-key metadata header.
type CrystalPackageServiceClient interface {
	ListCrystalPackages(ctx context.Context, in *ListCrystalPackagesRequest, opts ...grpc.CallOption) (*ListCrystalPackagesResponse, error)
	GetCrystalPackage(ctx context.Context, in *GetCrystalPackageRequest, opts ...grpc.CallOption) (*GetCrystalPackageResponse, error)
	CreateCrystalPackage(ctx context.Context, in *CreateCrystalPackageRequest, opts ...grpc.CallOption) (*CreateCrystalPackageResponse, error)
	UpdateCrystalPackage(ctx context.Context, in *UpdateCrystalPackageRequest, opts ...grpc.CallOption) (*UpdateCrystalPackageResponse, error)
}

type crystalPackageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrystalPackageServiceClient(cc grpc.ClientConnInterface) CrystalPackageServiceClient {
	return &crystalPackageServiceClient{cc}
}

func (c *crystalPackageServiceClient) ListCrystalPackages(ctx context.Context, in *ListCrystalPackagesRequest, opts ...grpc.CallOption) (*ListCrystalPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCrystalPackagesResponse)
	err := c.cc.Invoke(ctx, CrystalPackageService_ListCrystalPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crystalPackageServiceClient) GetCrystalPackage(ctx context.Context, in *GetCrystalPackageRequest, opts ...grpc.CallOption) (*GetCrystalPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCrystalPackageResponse)
	err := c.cc.Invoke(ctx, CrystalPackageService_GetCrystalPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crystalPackageServiceClient) CreateCrystalPackage(ctx context.Context, in *CreateCrystalPackageRequest, opts ...grpc.CallOption) (*CreateCrystalPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCrystalPackageResponse)
	err := c.cc.Invoke(ctx, CrystalPackageService_CreateCrystalPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crystalPackageServiceClient) UpdateCrystalPackage(ctx context.Context, in *UpdateCrystalPackageRequest, opts ...grpc.CallOption) (*UpdateCrystalPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCrystalPackageResponse)
	err := c.cc.Invoke(ctx, CrystalPackageService_UpdateCrystalPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrystalPackageServiceServer is the server API for CrystalPackageService service.
// All implementations must embed UnimplementedCrystalPackageServiceServer
// for forward compatibility.
//
// CrystalPackageService exposes admin CRUD operations for crystal packages.
// All RPCs require the x-internal-key metadata header.
type CrystalPackageServiceServer interface {
	ListCrystalPackages(context.Context, *ListCrystalPackagesRequest) (*ListCrystalPackagesResponse, error)
	GetCrystalPackage(context.Context, *GetCrystalPackageRequest) (*GetCrystalPackageResponse, error)
	CreateCrystalPackage(context.Context, *CreateCrystalPackageRequest) (*CreateCrystalPackageResponse, error)
	UpdateCrystalPackage(context.Context, *UpdateCrystalPackageRequest) (*UpdateCrystalPackageResponse, error)
	mustEmbedUnimplementedCrystalPackageServiceServer()
}

// UnimplementedCrystalPackageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrystalPackageServiceServer struct{}

func (UnimplementedCrystalPackageServiceServer) ListCrystalPackages(context.Context, *ListCrystalPackagesRequest) (*ListCrystalPackagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCrystalPackages not implemented")
}
func (UnimplementedCrystalPackageServiceServer) GetCrystalPackage(context.Context, *GetCrystalPackageRequest) (*GetCrystalPackageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCrystalPackage not implemented")
}
func (UnimplementedCrystalPackageServiceServer) CreateCrystalPackage(context.Context, *CreateCrystalPackageRequest) (*CreateCrystalPackageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCrystalPackage not implemented")
}
func (UnimplementedCrystalPackageServiceServer) UpdateCrystalPackage(context.Context, *UpdateCrystalPackageRequest) (*UpdateCrystalPackageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCrystalPackage not implemented")
}
func (UnimplementedCrystalPackageServiceServer) mustEmbedUnimplementedCrystalPackageServiceServer() {}
func (UnimplementedCrystalPackageServiceServer) testEmbeddedByValue()                               {}

// UnsafeCrystalPackageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrystalPackageServiceServer will
// result in compilation errors.
type UnsafeCrystalPackageServiceServer interface {
	mustEmbedUnimplementedCrystalPackageServiceServer()
}

func RegisterCrystalPackageServiceServer(s grpc.ServiceRegistrar, srv CrystalPackageServiceServer) {
	// If the following call pancis, it indicates UnimplementedCrystalPackageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrystalPackageService_ServiceDesc, srv)
}

func _CrystalPackageService_ListCrystalPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCrystalPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrystalPackageServiceServer).ListCrystalPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrystalPackageService_ListCrystalPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrystalPackageServiceServer).ListCrystalPackages(ctx, req.(*ListCrystalPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrystalPackageService_GetCrystalPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCrystalPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrystalPackageServiceServer).GetCrystalPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrystalPackageService_GetCrystalPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrystalPackageServiceServer).GetCrystalPackage(ctx, req.(*GetCrystalPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrystalPackageService_CreateCrystalPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCrystalPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrystalPackageServiceServer).CreateCrystalPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrystalPackageService_CreateCrystalPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrystalPackageServiceServer).CreateCrystalPackage(ctx, req.(*CreateCrystalPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrystalPackageService_UpdateCrystalPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCrystalPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrystalPackageServiceServer).UpdateCrystalPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrystalPackageService_UpdateCrystalPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrystalPackageServiceServer).UpdateCrystalPackage(ctx, req.(*UpdateCrystalPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrystalPackageService_ServiceDesc is the grpc.ServiceDesc for CrystalPackageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrystalPackageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.grpc.v1.CrystalPackageService",
	HandlerType: (*CrystalPackageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCrystalPackages",
			Handler:    _CrystalPackageService_ListCrystalPackages_Handler,
		},
		{
			MethodName: "GetCrystalPackage",
			Handler:    _CrystalPackageService_GetCrystalPackage_Handler,
		},
		{
			MethodName: "CreateCrystalPackage",
			Handler:    _CrystalPackageService_CreateCrystalPackage_Handler,
		},
		{
			MethodName: "UpdateCrystalPackage",
			Handler:    _CrystalPackageService_UpdateCrystalPackage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing/grpc/v1/private.proto",
}
