package domain

import (
	"time"

	"github.com/google/uuid"
)

// Admin is the central aggregate of the admin module.
// An admin is seeded with a username and a plain invite token.
// Registration is completed by calling Register, after which the admin can log in.
type Admin struct {
	ID           uuid.UUID
	Username     string
	PasswordHash *string // nil until Register is called
	InviteToken  *string // nil after Register is called
	Active       bool
	CreatedAt    int64 // unix seconds
	UpdatedAt    int64 // unix seconds
}

// NewAdmin constructs an unregistered Admin.
func NewAdmin(id uuid.UUID, username, inviteToken string) *Admin {
	now := NowUnix()
	return &Admin{
		ID:          id,
		Username:    username,
		InviteToken: &inviteToken,
		Active:      true,
		CreatedAt:   now,
		UpdatedAt:   now,
	}
}

// IsRegistered reports whether the admin has completed registration.
func (a *Admin) IsRegistered() bool {
	return a.PasswordHash != nil
}

// Register validates preconditions and completes the registration flow.
// The invite token is cleared on success so it cannot be reused.
func (a *Admin) Register(inviteToken, passwordHash string) error {
	if !a.Active {
		return NewError("error.domain.admin.not_active", nil)
	}
	if a.IsRegistered() {
		return NewError("error.domain.admin.already_registered", nil)
	}
	if a.InviteToken == nil || *a.InviteToken != inviteToken {
		return NewError("error.domain.admin.invalid_invite_token", nil)
	}
	a.PasswordHash = &passwordHash
	a.InviteToken = nil
	a.UpdatedAt = NowUnix()
	return nil
}

// CanAuthenticate checks that the admin is allowed to log in.
func (a *Admin) CanAuthenticate() error {
	if !a.Active {
		return NewError("error.domain.admin.not_active", nil)
	}
	if !a.IsRegistered() {
		return NewError("error.domain.admin.invalid_credentials", nil)
	}
	return nil
}

// SessionTTL is how long a newly issued session remains valid.
const SessionTTL = 7 * 24 * time.Hour

// Session is a server-side session record tied to an authenticated admin.
type Session struct {
	Token     string
	AdminID   uuid.UUID
	ExpiresAt int64 // unix seconds
	CreatedAt int64 // unix seconds
}

// NewSession constructs a session for an authenticated admin. The opaque token
// is generated by the infrastructure layer; the domain owns the session's
// lifecycle, deriving the expiry from SessionTTL.
func NewSession(adminID uuid.UUID, token string) *Session {
	now := NowUnix()
	return &Session{
		Token:     token,
		AdminID:   adminID,
		ExpiresAt: now + int64(SessionTTL.Seconds()),
		CreatedAt: now,
	}
}
