// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: game/grpc/v1/admin.proto

package gamev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PriceModel mirrors domain.PriceModel: resource costs in integer minor units.
type PriceModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credits       int64                  `protobuf:"varint,1,opt,name=credits,proto3" json:"credits,omitempty"`
	Iron          int64                  `protobuf:"varint,2,opt,name=iron,proto3" json:"iron,omitempty"`
	Titanium      int64                  `protobuf:"varint,3,opt,name=titanium,proto3" json:"titanium,omitempty"`
	Antimatter    int64                  `protobuf:"varint,4,opt,name=antimatter,proto3" json:"antimatter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceModel) Reset() {
	*x = PriceModel{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceModel) ProtoMessage() {}

func (x *PriceModel) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceModel.ProtoReflect.Descriptor instead.
func (*PriceModel) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *PriceModel) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *PriceModel) GetIron() int64 {
	if x != nil {
		return x.Iron
	}
	return 0
}

func (x *PriceModel) GetTitanium() int64 {
	if x != nil {
		return x.Titanium
	}
	return 0
}

func (x *PriceModel) GetAntimatter() int64 {
	if x != nil {
		return x.Antimatter
	}
	return 0
}

// ArmyPrototype is the wire shape of domain.ArmyItemPrototype.
//
// Enum-like fields (category, faction, creation_sources) are carried as strings
// rather than proto enums: the domain stores them as free string constants and
// the DB is the source of truth, so a parallel proto enum would be a second
// definition that could silently drift. unlock_technology_id is optional
// (absent = available by default).
type ArmyPrototype struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category           string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	CreationSources    []string               `protobuf:"bytes,4,rep,name=creation_sources,json=creationSources,proto3" json:"creation_sources,omitempty"`
	Faction            string                 `protobuf:"bytes,5,opt,name=faction,proto3" json:"faction,omitempty"`
	UnlockTechnologyId *int64                 `protobuf:"varint,6,opt,name=unlock_technology_id,json=unlockTechnologyId,proto3,oneof" json:"unlock_technology_id,omitempty"`
	ShortDescription   string                 `protobuf:"bytes,7,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	FullDescription    string                 `protobuf:"bytes,8,opt,name=full_description,json=fullDescription,proto3" json:"full_description,omitempty"`
	Price              *PriceModel            `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	ProductionTime     int64                  `protobuf:"varint,10,opt,name=production_time,json=productionTime,proto3" json:"production_time,omitempty"`
	Space              int32                  `protobuf:"varint,11,opt,name=space,proto3" json:"space,omitempty"`
	ImageUrl           string                 `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Attack             int32                  `protobuf:"varint,13,opt,name=attack,proto3" json:"attack,omitempty"`
	Defence            int32                  `protobuf:"varint,14,opt,name=defence,proto3" json:"defence,omitempty"`
	Capacity           int32                  `protobuf:"varint,15,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Stealth            int32                  `protobuf:"varint,16,opt,name=stealth,proto3" json:"stealth,omitempty"`
	Speed              int32                  `protobuf:"varint,17,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ArmyPrototype) Reset() {
	*x = ArmyPrototype{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmyPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmyPrototype) ProtoMessage() {}

func (x *ArmyPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmyPrototype.ProtoReflect.Descriptor instead.
func (*ArmyPrototype) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ArmyPrototype) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArmyPrototype) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArmyPrototype) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ArmyPrototype) GetCreationSources() []string {
	if x != nil {
		return x.CreationSources
	}
	return nil
}

func (x *ArmyPrototype) GetFaction() string {
	if x != nil {
		return x.Faction
	}
	return ""
}

func (x *ArmyPrototype) GetUnlockTechnologyId() int64 {
	if x != nil && x.UnlockTechnologyId != nil {
		return *x.UnlockTechnologyId
	}
	return 0
}

func (x *ArmyPrototype) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *ArmyPrototype) GetFullDescription() string {
	if x != nil {
		return x.FullDescription
	}
	return ""
}

func (x *ArmyPrototype) GetPrice() *PriceModel {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *ArmyPrototype) GetProductionTime() int64 {
	if x != nil {
		return x.ProductionTime
	}
	return 0
}

func (x *ArmyPrototype) GetSpace() int32 {
	if x != nil {
		return x.Space
	}
	return 0
}

func (x *ArmyPrototype) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ArmyPrototype) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *ArmyPrototype) GetDefence() int32 {
	if x != nil {
		return x.Defence
	}
	return 0
}

func (x *ArmyPrototype) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ArmyPrototype) GetStealth() int32 {
	if x != nil {
		return x.Stealth
	}
	return 0
}

func (x *ArmyPrototype) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type ListArmyPrototypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArmyPrototypesRequest) Reset() {
	*x = ListArmyPrototypesRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArmyPrototypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArmyPrototypesRequest) ProtoMessage() {}

func (x *ListArmyPrototypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArmyPrototypesRequest.ProtoReflect.Descriptor instead.
func (*ListArmyPrototypesRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{2}
}

type ListArmyPrototypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototypes    []*ArmyPrototype       `protobuf:"bytes,1,rep,name=prototypes,proto3" json:"prototypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArmyPrototypesResponse) Reset() {
	*x = ListArmyPrototypesResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArmyPrototypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArmyPrototypesResponse) ProtoMessage() {}

func (x *ListArmyPrototypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArmyPrototypesResponse.ProtoReflect.Descriptor instead.
func (*ListArmyPrototypesResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListArmyPrototypesResponse) GetPrototypes() []*ArmyPrototype {
	if x != nil {
		return x.Prototypes
	}
	return nil
}

type GetArmyPrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArmyPrototypeRequest) Reset() {
	*x = GetArmyPrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArmyPrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArmyPrototypeRequest) ProtoMessage() {}

func (x *GetArmyPrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArmyPrototypeRequest.ProtoReflect.Descriptor instead.
func (*GetArmyPrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetArmyPrototypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArmyPrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *ArmyPrototype         `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArmyPrototypeResponse) Reset() {
	*x = GetArmyPrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArmyPrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArmyPrototypeResponse) ProtoMessage() {}

func (x *GetArmyPrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArmyPrototypeResponse.ProtoReflect.Descriptor instead.
func (*GetArmyPrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetArmyPrototypeResponse) GetPrototype() *ArmyPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

// CreateArmyPrototypeRequest carries the prototype to insert. The caller MUST set
// a positive id: prototypes are ordered and each type occupies its own id range,
// so the id is chosen by the caller rather than assigned by the server.
type CreateArmyPrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *ArmyPrototype         `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArmyPrototypeRequest) Reset() {
	*x = CreateArmyPrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArmyPrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArmyPrototypeRequest) ProtoMessage() {}

func (x *CreateArmyPrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArmyPrototypeRequest.ProtoReflect.Descriptor instead.
func (*CreateArmyPrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *CreateArmyPrototypeRequest) GetPrototype() *ArmyPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

type CreateArmyPrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *ArmyPrototype         `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArmyPrototypeResponse) Reset() {
	*x = CreateArmyPrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArmyPrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArmyPrototypeResponse) ProtoMessage() {}

func (x *CreateArmyPrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArmyPrototypeResponse.ProtoReflect.Descriptor instead.
func (*CreateArmyPrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *CreateArmyPrototypeResponse) GetPrototype() *ArmyPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

// UpdateArmyPrototypeRequest overwrites the prototype identified by prototype.id.
type UpdateArmyPrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *ArmyPrototype         `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArmyPrototypeRequest) Reset() {
	*x = UpdateArmyPrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArmyPrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArmyPrototypeRequest) ProtoMessage() {}

func (x *UpdateArmyPrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArmyPrototypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateArmyPrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateArmyPrototypeRequest) GetPrototype() *ArmyPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

type UpdateArmyPrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *ArmyPrototype         `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArmyPrototypeResponse) Reset() {
	*x = UpdateArmyPrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArmyPrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArmyPrototypeResponse) ProtoMessage() {}

func (x *UpdateArmyPrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArmyPrototypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateArmyPrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateArmyPrototypeResponse) GetPrototype() *ArmyPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

type BuildControlData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subtype       string                 `protobuf:"bytes,1,opt,name=subtype,proto3" json:"subtype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildControlData) Reset() {
	*x = BuildControlData{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildControlData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildControlData) ProtoMessage() {}

func (x *BuildControlData) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildControlData.ProtoReflect.Descriptor instead.
func (*BuildControlData) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *BuildControlData) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

type BuildResourcesData struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CreditsProduction    float64                `protobuf:"fixed64,1,opt,name=credits_production,json=creditsProduction,proto3" json:"credits_production,omitempty"`
	IronProduction       float64                `protobuf:"fixed64,2,opt,name=iron_production,json=ironProduction,proto3" json:"iron_production,omitempty"`
	TitaniumProduction   float64                `protobuf:"fixed64,3,opt,name=titanium_production,json=titaniumProduction,proto3" json:"titanium_production,omitempty"`
	AntimatterProduction float64                `protobuf:"fixed64,4,opt,name=antimatter_production,json=antimatterProduction,proto3" json:"antimatter_production,omitempty"`
	CreditsCapacity      int32                  `protobuf:"varint,5,opt,name=credits_capacity,json=creditsCapacity,proto3" json:"credits_capacity,omitempty"`
	IronCapacity         int32                  `protobuf:"varint,6,opt,name=iron_capacity,json=ironCapacity,proto3" json:"iron_capacity,omitempty"`
	TitaniumCapacity     int32                  `protobuf:"varint,7,opt,name=titanium_capacity,json=titaniumCapacity,proto3" json:"titanium_capacity,omitempty"`
	AntimatterCapacity   int32                  `protobuf:"varint,8,opt,name=antimatter_capacity,json=antimatterCapacity,proto3" json:"antimatter_capacity,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BuildResourcesData) Reset() {
	*x = BuildResourcesData{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResourcesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResourcesData) ProtoMessage() {}

func (x *BuildResourcesData) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResourcesData.ProtoReflect.Descriptor instead.
func (*BuildResourcesData) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *BuildResourcesData) GetCreditsProduction() float64 {
	if x != nil {
		return x.CreditsProduction
	}
	return 0
}

func (x *BuildResourcesData) GetIronProduction() float64 {
	if x != nil {
		return x.IronProduction
	}
	return 0
}

func (x *BuildResourcesData) GetTitaniumProduction() float64 {
	if x != nil {
		return x.TitaniumProduction
	}
	return 0
}

func (x *BuildResourcesData) GetAntimatterProduction() float64 {
	if x != nil {
		return x.AntimatterProduction
	}
	return 0
}

func (x *BuildResourcesData) GetCreditsCapacity() int32 {
	if x != nil {
		return x.CreditsCapacity
	}
	return 0
}

func (x *BuildResourcesData) GetIronCapacity() int32 {
	if x != nil {
		return x.IronCapacity
	}
	return 0
}

func (x *BuildResourcesData) GetTitaniumCapacity() int32 {
	if x != nil {
		return x.TitaniumCapacity
	}
	return 0
}

func (x *BuildResourcesData) GetAntimatterCapacity() int32 {
	if x != nil {
		return x.AntimatterCapacity
	}
	return 0
}

type BuildDefenseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefenceBonus  int32                  `protobuf:"varint,1,opt,name=defence_bonus,json=defenceBonus,proto3" json:"defence_bonus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildDefenseData) Reset() {
	*x = BuildDefenseData{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildDefenseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildDefenseData) ProtoMessage() {}

func (x *BuildDefenseData) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildDefenseData.ProtoReflect.Descriptor instead.
func (*BuildDefenseData) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *BuildDefenseData) GetDefenceBonus() int32 {
	if x != nil {
		return x.DefenceBonus
	}
	return 0
}

type BuildMilitaryData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UnlockArmyCategory string                 `protobuf:"bytes,1,opt,name=unlock_army_category,json=unlockArmyCategory,proto3" json:"unlock_army_category,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BuildMilitaryData) Reset() {
	*x = BuildMilitaryData{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildMilitaryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildMilitaryData) ProtoMessage() {}

func (x *BuildMilitaryData) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildMilitaryData.ProtoReflect.Descriptor instead.
func (*BuildMilitaryData) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *BuildMilitaryData) GetUnlockArmyCategory() string {
	if x != nil {
		return x.UnlockArmyCategory
	}
	return ""
}

type BuildIntelligenceData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Subtype         string                 `protobuf:"bytes,1,opt,name=subtype,proto3" json:"subtype,omitempty"`
	StealthStrength int32                  `protobuf:"varint,2,opt,name=stealth_strength,json=stealthStrength,proto3" json:"stealth_strength,omitempty"`
	ScanRange       int32                  `protobuf:"varint,3,opt,name=scan_range,json=scanRange,proto3" json:"scan_range,omitempty"`
	ScanCooldown    int64                  `protobuf:"varint,4,opt,name=scan_cooldown,json=scanCooldown,proto3" json:"scan_cooldown,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BuildIntelligenceData) Reset() {
	*x = BuildIntelligenceData{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildIntelligenceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildIntelligenceData) ProtoMessage() {}

func (x *BuildIntelligenceData) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildIntelligenceData.ProtoReflect.Descriptor instead.
func (*BuildIntelligenceData) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *BuildIntelligenceData) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *BuildIntelligenceData) GetStealthStrength() int32 {
	if x != nil {
		return x.StealthStrength
	}
	return 0
}

func (x *BuildIntelligenceData) GetScanRange() int32 {
	if x != nil {
		return x.ScanRange
	}
	return 0
}

func (x *BuildIntelligenceData) GetScanCooldown() int64 {
	if x != nil {
		return x.ScanCooldown
	}
	return 0
}

// BuildPrototype is the wire shape of domain.BuildItemPrototype. Like
// ArmyPrototype, enum-like fields (category, faction, creation_sources, and the
// subtype/unlock_army_category fields inside the data blocks) are carried as
// strings because the DB is the source of truth. unlock_technology_id is
// optional (absent = available by default).
//
// category_data is a oneof: exactly one block is present and it must match the
// category string. The mutual-exclusivity constraint is encoded in the schema
// rather than relying solely on application-layer validation.
type BuildPrototype struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category           string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	CreationSources    []string               `protobuf:"bytes,4,rep,name=creation_sources,json=creationSources,proto3" json:"creation_sources,omitempty"`
	Faction            string                 `protobuf:"bytes,5,opt,name=faction,proto3" json:"faction,omitempty"`
	UnlockTechnologyId *int64                 `protobuf:"varint,6,opt,name=unlock_technology_id,json=unlockTechnologyId,proto3,oneof" json:"unlock_technology_id,omitempty"`
	ShortDescription   string                 `protobuf:"bytes,7,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	FullDescription    string                 `protobuf:"bytes,8,opt,name=full_description,json=fullDescription,proto3" json:"full_description,omitempty"`
	Price              *PriceModel            `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	ProductionTime     int64                  `protobuf:"varint,10,opt,name=production_time,json=productionTime,proto3" json:"production_time,omitempty"`
	Space              int32                  `protobuf:"varint,11,opt,name=space,proto3" json:"space,omitempty"`
	ImageUrl           string                 `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// Types that are valid to be assigned to CategoryData:
	//
	//	*BuildPrototype_ControlData
	//	*BuildPrototype_ResourcesData
	//	*BuildPrototype_DefenseData
	//	*BuildPrototype_MilitaryData
	//	*BuildPrototype_IntelligenceData
	CategoryData  isBuildPrototype_CategoryData `protobuf_oneof:"category_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildPrototype) Reset() {
	*x = BuildPrototype{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildPrototype) ProtoMessage() {}

func (x *BuildPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildPrototype.ProtoReflect.Descriptor instead.
func (*BuildPrototype) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *BuildPrototype) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuildPrototype) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildPrototype) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BuildPrototype) GetCreationSources() []string {
	if x != nil {
		return x.CreationSources
	}
	return nil
}

func (x *BuildPrototype) GetFaction() string {
	if x != nil {
		return x.Faction
	}
	return ""
}

func (x *BuildPrototype) GetUnlockTechnologyId() int64 {
	if x != nil && x.UnlockTechnologyId != nil {
		return *x.UnlockTechnologyId
	}
	return 0
}

func (x *BuildPrototype) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *BuildPrototype) GetFullDescription() string {
	if x != nil {
		return x.FullDescription
	}
	return ""
}

func (x *BuildPrototype) GetPrice() *PriceModel {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *BuildPrototype) GetProductionTime() int64 {
	if x != nil {
		return x.ProductionTime
	}
	return 0
}

func (x *BuildPrototype) GetSpace() int32 {
	if x != nil {
		return x.Space
	}
	return 0
}

func (x *BuildPrototype) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *BuildPrototype) GetCategoryData() isBuildPrototype_CategoryData {
	if x != nil {
		return x.CategoryData
	}
	return nil
}

func (x *BuildPrototype) GetControlData() *BuildControlData {
	if x != nil {
		if x, ok := x.CategoryData.(*BuildPrototype_ControlData); ok {
			return x.ControlData
		}
	}
	return nil
}

func (x *BuildPrototype) GetResourcesData() *BuildResourcesData {
	if x != nil {
		if x, ok := x.CategoryData.(*BuildPrototype_ResourcesData); ok {
			return x.ResourcesData
		}
	}
	return nil
}

func (x *BuildPrototype) GetDefenseData() *BuildDefenseData {
	if x != nil {
		if x, ok := x.CategoryData.(*BuildPrototype_DefenseData); ok {
			return x.DefenseData
		}
	}
	return nil
}

func (x *BuildPrototype) GetMilitaryData() *BuildMilitaryData {
	if x != nil {
		if x, ok := x.CategoryData.(*BuildPrototype_MilitaryData); ok {
			return x.MilitaryData
		}
	}
	return nil
}

func (x *BuildPrototype) GetIntelligenceData() *BuildIntelligenceData {
	if x != nil {
		if x, ok := x.CategoryData.(*BuildPrototype_IntelligenceData); ok {
			return x.IntelligenceData
		}
	}
	return nil
}

type isBuildPrototype_CategoryData interface {
	isBuildPrototype_CategoryData()
}

type BuildPrototype_ControlData struct {
	ControlData *BuildControlData `protobuf:"bytes,13,opt,name=control_data,json=controlData,proto3,oneof"`
}

type BuildPrototype_ResourcesData struct {
	ResourcesData *BuildResourcesData `protobuf:"bytes,14,opt,name=resources_data,json=resourcesData,proto3,oneof"`
}

type BuildPrototype_DefenseData struct {
	DefenseData *BuildDefenseData `protobuf:"bytes,15,opt,name=defense_data,json=defenseData,proto3,oneof"`
}

type BuildPrototype_MilitaryData struct {
	MilitaryData *BuildMilitaryData `protobuf:"bytes,16,opt,name=military_data,json=militaryData,proto3,oneof"`
}

type BuildPrototype_IntelligenceData struct {
	IntelligenceData *BuildIntelligenceData `protobuf:"bytes,17,opt,name=intelligence_data,json=intelligenceData,proto3,oneof"`
}

func (*BuildPrototype_ControlData) isBuildPrototype_CategoryData() {}

func (*BuildPrototype_ResourcesData) isBuildPrototype_CategoryData() {}

func (*BuildPrototype_DefenseData) isBuildPrototype_CategoryData() {}

func (*BuildPrototype_MilitaryData) isBuildPrototype_CategoryData() {}

func (*BuildPrototype_IntelligenceData) isBuildPrototype_CategoryData() {}

type ListBuildPrototypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildPrototypesRequest) Reset() {
	*x = ListBuildPrototypesRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildPrototypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildPrototypesRequest) ProtoMessage() {}

func (x *ListBuildPrototypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildPrototypesRequest.ProtoReflect.Descriptor instead.
func (*ListBuildPrototypesRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{16}
}

type ListBuildPrototypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototypes    []*BuildPrototype      `protobuf:"bytes,1,rep,name=prototypes,proto3" json:"prototypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildPrototypesResponse) Reset() {
	*x = ListBuildPrototypesResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildPrototypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildPrototypesResponse) ProtoMessage() {}

func (x *ListBuildPrototypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildPrototypesResponse.ProtoReflect.Descriptor instead.
func (*ListBuildPrototypesResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *ListBuildPrototypesResponse) GetPrototypes() []*BuildPrototype {
	if x != nil {
		return x.Prototypes
	}
	return nil
}

type GetBuildPrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildPrototypeRequest) Reset() {
	*x = GetBuildPrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildPrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildPrototypeRequest) ProtoMessage() {}

func (x *GetBuildPrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildPrototypeRequest.ProtoReflect.Descriptor instead.
func (*GetBuildPrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *GetBuildPrototypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBuildPrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *BuildPrototype        `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildPrototypeResponse) Reset() {
	*x = GetBuildPrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildPrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildPrototypeResponse) ProtoMessage() {}

func (x *GetBuildPrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildPrototypeResponse.ProtoReflect.Descriptor instead.
func (*GetBuildPrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *GetBuildPrototypeResponse) GetPrototype() *BuildPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

// CreateBuildPrototypeRequest carries the prototype to insert. The caller MUST set
// a positive id: prototypes are ordered and each type occupies its own id range,
// so the id is chosen by the caller rather than assigned by the server.
type CreateBuildPrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *BuildPrototype        `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildPrototypeRequest) Reset() {
	*x = CreateBuildPrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildPrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildPrototypeRequest) ProtoMessage() {}

func (x *CreateBuildPrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildPrototypeRequest.ProtoReflect.Descriptor instead.
func (*CreateBuildPrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *CreateBuildPrototypeRequest) GetPrototype() *BuildPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

type CreateBuildPrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *BuildPrototype        `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildPrototypeResponse) Reset() {
	*x = CreateBuildPrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildPrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildPrototypeResponse) ProtoMessage() {}

func (x *CreateBuildPrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildPrototypeResponse.ProtoReflect.Descriptor instead.
func (*CreateBuildPrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *CreateBuildPrototypeResponse) GetPrototype() *BuildPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

// UpdateBuildPrototypeRequest overwrites the prototype identified by prototype.id.
type UpdateBuildPrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *BuildPrototype        `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBuildPrototypeRequest) Reset() {
	*x = UpdateBuildPrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBuildPrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBuildPrototypeRequest) ProtoMessage() {}

func (x *UpdateBuildPrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBuildPrototypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateBuildPrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateBuildPrototypeRequest) GetPrototype() *BuildPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

type UpdateBuildPrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *BuildPrototype        `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBuildPrototypeResponse) Reset() {
	*x = UpdateBuildPrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBuildPrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBuildPrototypeResponse) ProtoMessage() {}

func (x *UpdateBuildPrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBuildPrototypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateBuildPrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateBuildPrototypeResponse) GetPrototype() *BuildPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

type StorageBuffData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value           float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StorageBuffData) Reset() {
	*x = StorageBuffData{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBuffData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBuffData) ProtoMessage() {}

func (x *StorageBuffData) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBuffData.ProtoReflect.Descriptor instead.
func (*StorageBuffData) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *StorageBuffData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StorageBuffData) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StorageBuffData) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type StorageIntelData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DecryptionSeconds int64                  `protobuf:"varint,2,opt,name=decryption_seconds,json=decryptionSeconds,proto3" json:"decryption_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StorageIntelData) Reset() {
	*x = StorageIntelData{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageIntelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageIntelData) ProtoMessage() {}

func (x *StorageIntelData) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageIntelData.ProtoReflect.Descriptor instead.
func (*StorageIntelData) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *StorageIntelData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StorageIntelData) GetDecryptionSeconds() int64 {
	if x != nil {
		return x.DecryptionSeconds
	}
	return 0
}

// StorageDamagedData describes how to restore a damaged army unit.
// original_unit_id references the ArmyItemPrototype the item restores into.
type StorageDamagedData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RestorePrice       *PriceModel            `protobuf:"bytes,1,opt,name=restore_price,json=restorePrice,proto3" json:"restore_price,omitempty"`
	RestorationSeconds int64                  `protobuf:"varint,2,opt,name=restoration_seconds,json=restorationSeconds,proto3" json:"restoration_seconds,omitempty"`
	OriginalUnitId     int64                  `protobuf:"varint,3,opt,name=original_unit_id,json=originalUnitId,proto3" json:"original_unit_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StorageDamagedData) Reset() {
	*x = StorageDamagedData{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDamagedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDamagedData) ProtoMessage() {}

func (x *StorageDamagedData) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDamagedData.ProtoReflect.Descriptor instead.
func (*StorageDamagedData) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *StorageDamagedData) GetRestorePrice() *PriceModel {
	if x != nil {
		return x.RestorePrice
	}
	return nil
}

func (x *StorageDamagedData) GetRestorationSeconds() int64 {
	if x != nil {
		return x.RestorationSeconds
	}
	return 0
}

func (x *StorageDamagedData) GetOriginalUnitId() int64 {
	if x != nil {
		return x.OriginalUnitId
	}
	return 0
}

type StorageArtifactData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageArtifactData) Reset() {
	*x = StorageArtifactData{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageArtifactData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageArtifactData) ProtoMessage() {}

func (x *StorageArtifactData) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageArtifactData.ProtoReflect.Descriptor instead.
func (*StorageArtifactData) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{27}
}

func (x *StorageArtifactData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StorageArtifactData) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StorageConsumableData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	BoxContents   []string               `protobuf:"bytes,2,rep,name=box_contents,json=boxContents,proto3" json:"box_contents,omitempty"`
	BoxSize       int32                  `protobuf:"varint,3,opt,name=box_size,json=boxSize,proto3" json:"box_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageConsumableData) Reset() {
	*x = StorageConsumableData{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageConsumableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConsumableData) ProtoMessage() {}

func (x *StorageConsumableData) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConsumableData.ProtoReflect.Descriptor instead.
func (*StorageConsumableData) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *StorageConsumableData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StorageConsumableData) GetBoxContents() []string {
	if x != nil {
		return x.BoxContents
	}
	return nil
}

func (x *StorageConsumableData) GetBoxSize() int32 {
	if x != nil {
		return x.BoxSize
	}
	return 0
}

// StoragePrototype is the wire shape of domain.StorageItemPrototype. Like the
// other prototype types, enum-like fields (category, creation_sources, and the
// type fields inside data blocks) are carried as strings because the DB is the
// source of truth. estimated_worth is a rough credit value used in trading.
//
// category_data is a oneof: exactly one block is present and it must match the
// category string.
type StoragePrototype struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category         string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	CreationSources  []string               `protobuf:"bytes,4,rep,name=creation_sources,json=creationSources,proto3" json:"creation_sources,omitempty"`
	EstimatedWorth   int32                  `protobuf:"varint,5,opt,name=estimated_worth,json=estimatedWorth,proto3" json:"estimated_worth,omitempty"`
	ShortDescription string                 `protobuf:"bytes,6,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	FullDescription  string                 `protobuf:"bytes,7,opt,name=full_description,json=fullDescription,proto3" json:"full_description,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// Types that are valid to be assigned to CategoryData:
	//
	//	*StoragePrototype_BuffData
	//	*StoragePrototype_IntelData
	//	*StoragePrototype_DamagedData
	//	*StoragePrototype_ArtifactData
	//	*StoragePrototype_ConsumableData
	CategoryData  isStoragePrototype_CategoryData `protobuf_oneof:"category_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoragePrototype) Reset() {
	*x = StoragePrototype{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePrototype) ProtoMessage() {}

func (x *StoragePrototype) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePrototype.ProtoReflect.Descriptor instead.
func (*StoragePrototype) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *StoragePrototype) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoragePrototype) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoragePrototype) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *StoragePrototype) GetCreationSources() []string {
	if x != nil {
		return x.CreationSources
	}
	return nil
}

func (x *StoragePrototype) GetEstimatedWorth() int32 {
	if x != nil {
		return x.EstimatedWorth
	}
	return 0
}

func (x *StoragePrototype) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *StoragePrototype) GetFullDescription() string {
	if x != nil {
		return x.FullDescription
	}
	return ""
}

func (x *StoragePrototype) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *StoragePrototype) GetCategoryData() isStoragePrototype_CategoryData {
	if x != nil {
		return x.CategoryData
	}
	return nil
}

func (x *StoragePrototype) GetBuffData() *StorageBuffData {
	if x != nil {
		if x, ok := x.CategoryData.(*StoragePrototype_BuffData); ok {
			return x.BuffData
		}
	}
	return nil
}

func (x *StoragePrototype) GetIntelData() *StorageIntelData {
	if x != nil {
		if x, ok := x.CategoryData.(*StoragePrototype_IntelData); ok {
			return x.IntelData
		}
	}
	return nil
}

func (x *StoragePrototype) GetDamagedData() *StorageDamagedData {
	if x != nil {
		if x, ok := x.CategoryData.(*StoragePrototype_DamagedData); ok {
			return x.DamagedData
		}
	}
	return nil
}

func (x *StoragePrototype) GetArtifactData() *StorageArtifactData {
	if x != nil {
		if x, ok := x.CategoryData.(*StoragePrototype_ArtifactData); ok {
			return x.ArtifactData
		}
	}
	return nil
}

func (x *StoragePrototype) GetConsumableData() *StorageConsumableData {
	if x != nil {
		if x, ok := x.CategoryData.(*StoragePrototype_ConsumableData); ok {
			return x.ConsumableData
		}
	}
	return nil
}

type isStoragePrototype_CategoryData interface {
	isStoragePrototype_CategoryData()
}

type StoragePrototype_BuffData struct {
	BuffData *StorageBuffData `protobuf:"bytes,9,opt,name=buff_data,json=buffData,proto3,oneof"`
}

type StoragePrototype_IntelData struct {
	IntelData *StorageIntelData `protobuf:"bytes,10,opt,name=intel_data,json=intelData,proto3,oneof"`
}

type StoragePrototype_DamagedData struct {
	DamagedData *StorageDamagedData `protobuf:"bytes,11,opt,name=damaged_data,json=damagedData,proto3,oneof"`
}

type StoragePrototype_ArtifactData struct {
	ArtifactData *StorageArtifactData `protobuf:"bytes,12,opt,name=artifact_data,json=artifactData,proto3,oneof"`
}

type StoragePrototype_ConsumableData struct {
	ConsumableData *StorageConsumableData `protobuf:"bytes,13,opt,name=consumable_data,json=consumableData,proto3,oneof"`
}

func (*StoragePrototype_BuffData) isStoragePrototype_CategoryData() {}

func (*StoragePrototype_IntelData) isStoragePrototype_CategoryData() {}

func (*StoragePrototype_DamagedData) isStoragePrototype_CategoryData() {}

func (*StoragePrototype_ArtifactData) isStoragePrototype_CategoryData() {}

func (*StoragePrototype_ConsumableData) isStoragePrototype_CategoryData() {}

type ListStoragePrototypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoragePrototypesRequest) Reset() {
	*x = ListStoragePrototypesRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoragePrototypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoragePrototypesRequest) ProtoMessage() {}

func (x *ListStoragePrototypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoragePrototypesRequest.ProtoReflect.Descriptor instead.
func (*ListStoragePrototypesRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{30}
}

type ListStoragePrototypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototypes    []*StoragePrototype    `protobuf:"bytes,1,rep,name=prototypes,proto3" json:"prototypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoragePrototypesResponse) Reset() {
	*x = ListStoragePrototypesResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoragePrototypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoragePrototypesResponse) ProtoMessage() {}

func (x *ListStoragePrototypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoragePrototypesResponse.ProtoReflect.Descriptor instead.
func (*ListStoragePrototypesResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{31}
}

func (x *ListStoragePrototypesResponse) GetPrototypes() []*StoragePrototype {
	if x != nil {
		return x.Prototypes
	}
	return nil
}

type GetStoragePrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoragePrototypeRequest) Reset() {
	*x = GetStoragePrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoragePrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoragePrototypeRequest) ProtoMessage() {}

func (x *GetStoragePrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoragePrototypeRequest.ProtoReflect.Descriptor instead.
func (*GetStoragePrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{32}
}

func (x *GetStoragePrototypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStoragePrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *StoragePrototype      `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoragePrototypeResponse) Reset() {
	*x = GetStoragePrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoragePrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoragePrototypeResponse) ProtoMessage() {}

func (x *GetStoragePrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoragePrototypeResponse.ProtoReflect.Descriptor instead.
func (*GetStoragePrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{33}
}

func (x *GetStoragePrototypeResponse) GetPrototype() *StoragePrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

// CreateStoragePrototypeRequest carries the prototype to insert. The caller MUST
// set a positive id: prototypes are ordered and each type occupies its own id range,
// so the id is chosen by the caller rather than assigned by the server.
type CreateStoragePrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *StoragePrototype      `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoragePrototypeRequest) Reset() {
	*x = CreateStoragePrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoragePrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoragePrototypeRequest) ProtoMessage() {}

func (x *CreateStoragePrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoragePrototypeRequest.ProtoReflect.Descriptor instead.
func (*CreateStoragePrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{34}
}

func (x *CreateStoragePrototypeRequest) GetPrototype() *StoragePrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

type CreateStoragePrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *StoragePrototype      `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoragePrototypeResponse) Reset() {
	*x = CreateStoragePrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoragePrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoragePrototypeResponse) ProtoMessage() {}

func (x *CreateStoragePrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoragePrototypeResponse.ProtoReflect.Descriptor instead.
func (*CreateStoragePrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{35}
}

func (x *CreateStoragePrototypeResponse) GetPrototype() *StoragePrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

// UpdateStoragePrototypeRequest overwrites the prototype identified by prototype.id.
type UpdateStoragePrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *StoragePrototype      `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStoragePrototypeRequest) Reset() {
	*x = UpdateStoragePrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStoragePrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoragePrototypeRequest) ProtoMessage() {}

func (x *UpdateStoragePrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoragePrototypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateStoragePrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateStoragePrototypeRequest) GetPrototype() *StoragePrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

type UpdateStoragePrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *StoragePrototype      `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStoragePrototypeResponse) Reset() {
	*x = UpdateStoragePrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStoragePrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoragePrototypeResponse) ProtoMessage() {}

func (x *UpdateStoragePrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoragePrototypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateStoragePrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{37}
}

func (x *UpdateStoragePrototypeResponse) GetPrototype() *StoragePrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

var File_game_grpc_v1_admin_proto protoreflect.FileDescriptor

const file_game_grpc_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x18game/grpc/v1/admin.proto\x12\fgame.grpc.v1\"v\n" +
	"\n" +
	"PriceModel\x12\x18\n" +
	"\acredits\x18\x01 \x01(\x03R\acredits\x12\x12\n" +
	"\x04iron\x18\x02 \x01(\x03R\x04iron\x12\x1a\n" +
	"\btitanium\x18\x03 \x01(\x03R\btitanium\x12\x1e\n" +
	"\n" +
	"antimatter\x18\x04 \x01(\x03R\n" +
	"antimatter\"\xc6\x04\n" +
	"\rArmyPrototype\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12)\n" +
	"\x10creation_sources\x18\x04 \x03(\tR\x0fcreationSources\x12\x18\n" +
	"\afaction\x18\x05 \x01(\tR\afaction\x125\n" +
	"\x14unlock_technology_id\x18\x06 \x01(\x03H\x00R\x12unlockTechnologyId\x88\x01\x01\x12+\n" +
	"\x11short_description\x18\a \x01(\tR\x10shortDescription\x12)\n" +
	"\x10full_description\x18\b \x01(\tR\x0ffullDescription\x12.\n" +
	"\x05price\x18\t \x01(\v2\x18.game.grpc.v1.PriceModelR\x05price\x12'\n" +
	"\x0fproduction_time\x18\n" +
	" \x01(\x03R\x0eproductionTime\x12\x14\n" +
	"\x05space\x18\v \x01(\x05R\x05space\x12\x1b\n" +
	"\timage_url\x18\f \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06attack\x18\r \x01(\x05R\x06attack\x12\x18\n" +
	"\adefence\x18\x0e \x01(\x05R\adefence\x12\x1a\n" +
	"\bcapacity\x18\x0f \x01(\x05R\bcapacity\x12\x18\n" +
	"\astealth\x18\x10 \x01(\x05R\astealth\x12\x14\n" +
	"\x05speed\x18\x11 \x01(\x05R\x05speedB\x17\n" +
	"\x15_unlock_technology_id\"\x1b\n" +
	"\x19ListArmyPrototypesRequest\"Y\n" +
	"\x1aListArmyPrototypesResponse\x12;\n" +
	"\n" +
	"prototypes\x18\x01 \x03(\v2\x1b.game.grpc.v1.ArmyPrototypeR\n" +
	"prototypes\")\n" +
	"\x17GetArmyPrototypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"U\n" +
	"\x18GetArmyPrototypeResponse\x129\n" +
	"\tprototype\x18\x01 \x01(\v2\x1b.game.grpc.v1.ArmyPrototypeR\tprototype\"W\n" +
	"\x1aCreateArmyPrototypeRequest\x129\n" +
	"\tprototype\x18\x01 \x01(\v2\x1b.game.grpc.v1.ArmyPrototypeR\tprototype\"X\n" +
	"\x1bCreateArmyPrototypeResponse\x129\n" +
	"\tprototype\x18\x01 \x01(\v2\x1b.game.grpc.v1.ArmyPrototypeR\tprototype\"W\n" +
	"\x1aUpdateArmyPrototypeRequest\x129\n" +
	"\tprototype\x18\x01 \x01(\v2\x1b.game.grpc.v1.ArmyPrototypeR\tprototype\"X\n" +
	"\x1bUpdateArmyPrototypeResponse\x129\n" +
	"\tprototype\x18\x01 \x01(\v2\x1b.game.grpc.v1.ArmyPrototypeR\tprototype\",\n" +
	"\x10BuildControlData\x12\x18\n" +
	"\asubtype\x18\x01 \x01(\tR\asubtype\"\x80\x03\n" +
	"\x12BuildResourcesData\x12-\n" +
	"\x12credits_production\x18\x01 \x01(\x01R\x11creditsProduction\x12'\n" +
	"\x0firon_production\x18\x02 \x01(\x01R\x0eironProduction\x12/\n" +
	"\x13titanium_production\x18\x03 \x01(\x01R\x12titaniumProduction\x123\n" +
	"\x15antimatter_production\x18\x04 \x01(\x01R\x14antimatterProduction\x12)\n" +
	"\x10credits_capacity\x18\x05 \x01(\x05R\x0fcreditsCapacity\x12#\n" +
	"\riron_capacity\x18\x06 \x01(\x05R\fironCapacity\x12+\n" +
	"\x11titanium_capacity\x18\a \x01(\x05R\x10titaniumCapacity\x12/\n" +
	"\x13antimatter_capacity\x18\b \x01(\x05R\x12antimatterCapacity\"7\n" +
	"\x10BuildDefenseData\x12#\n" +
	"\rdefence_bonus\x18\x01 \x01(\x05R\fdefenceBonus\"E\n" +
	"\x11BuildMilitaryData\x120\n" +
	"\x14unlock_army_category\x18\x01 \x01(\tR\x12unlockArmyCategory\"\xa0\x01\n" +
	"\x15BuildIntelligenceData\x12\x18\n" +
	"\asubtype\x18\x01 \x01(\tR\asubtype\x12)\n" +
	"\x10stealth_strength\x18\x02 \x01(\x05R\x0fstealthStrength\x12\x1d\n" +
	"\n" +
	"scan_range\x18\x03 \x01(\x05R\tscanRange\x12#\n" +
	"\rscan_cooldown\x18\x04 \x01(\x03R\fscanCooldown\"\xcb\x06\n" +
	"\x0eBuildPrototype\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12)\n" +
	"\x10creation_sources\x18\x04 \x03(\tR\x0fcreationSources\x12\x18\n" +
	"\afaction\x18\x05 \x01(\tR\afaction\x125\n" +
	"\x14unlock_technology_id\x18\x06 \x01(\x03H\x01R\x12unlockTechnologyId\x88\x01\x01\x12+\n" +
	"\x11short_description\x18\a \x01(\tR\x10shortDescription\x12)\n" +
	"\x10full_description\x18\b \x01(\tR\x0ffullDescription\x12.\n" +
	"\x05price\x18\t \x01(\v2\x18.game.grpc.v1.PriceModelR\x05price\x12'\n" +
	"\x0fproduction_time\x18\n" +
	" \x01(\x03R\x0eproductionTime\x12\x14\n" +
	"\x05space\x18\v \x01(\x05R\x05space\x12\x1b\n" +
	"\timage_url\x18\f \x01(\tR\bimageUrl\x12C\n" +
	"\fcontrol_data\x18\r \x01(\v2\x1e.game.grpc.v1.BuildControlDataH\x00R\vcontrolData\x12I\n" +
	"\x0eresources_data\x18\x0e \x01(\v2 .game.grpc.v1.BuildResourcesDataH\x00R\rresourcesData\x12C\n" +
	"\fdefense_data\x18\x0f \x01(\v2\x1e.game.grpc.v1.BuildDefenseDataH\x00R\vdefenseData\x12F\n" +
	"\rmilitary_data\x18\x10 \x01(\v2\x1f.game.grpc.v1.BuildMilitaryDataH\x00R\fmilitaryData\x12R\n" +
	"\x11intelligence_data\x18\x11 \x01(\v2#.game.grpc.v1.BuildIntelligenceDataH\x00R\x10intelligenceDataB\x0f\n" +
	"\rcategory_dataB\x17\n" +
	"\x15_unlock_technology_id\"\x1c\n" +
	"\x1aListBuildPrototypesRequest\"[\n" +
	"\x1bListBuildPrototypesResponse\x12<\n" +
	"\n" +
	"prototypes\x18\x01 \x03(\v2\x1c.game.grpc.v1.BuildPrototypeR\n" +
	"prototypes\"*\n" +
	"\x18GetBuildPrototypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"W\n" +
	"\x19GetBuildPrototypeResponse\x12:\n" +
	"\tprototype\x18\x01 \x01(\v2\x1c.game.grpc.v1.BuildPrototypeR\tprototype\"Y\n" +
	"\x1bCreateBuildPrototypeRequest\x12:\n" +
	"\tprototype\x18\x01 \x01(\v2\x1c.game.grpc.v1.BuildPrototypeR\tprototype\"Z\n" +
	"\x1cCreateBuildPrototypeResponse\x12:\n" +
	"\tprototype\x18\x01 \x01(\v2\x1c.game.grpc.v1.BuildPrototypeR\tprototype\"Y\n" +
	"\x1bUpdateBuildPrototypeRequest\x12:\n" +
	"\tprototype\x18\x01 \x01(\v2\x1c.game.grpc.v1.BuildPrototypeR\tprototype\"Z\n" +
	"\x1cUpdateBuildPrototypeResponse\x12:\n" +
	"\tprototype\x18\x01 \x01(\v2\x1c.game.grpc.v1.BuildPrototypeR\tprototype\"f\n" +
	"\x0fStorageBuffData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x03R\x0fdurationSeconds\"U\n" +
	"\x10StorageIntelData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12-\n" +
	"\x12decryption_seconds\x18\x02 \x01(\x03R\x11decryptionSeconds\"\xae\x01\n" +
	"\x12StorageDamagedData\x12=\n" +
	"\rrestore_price\x18\x01 \x01(\v2\x18.game.grpc.v1.PriceModelR\frestorePrice\x12/\n" +
	"\x13restoration_seconds\x18\x02 \x01(\x03R\x12restorationSeconds\x12(\n" +
	"\x10original_unit_id\x18\x03 \x01(\x03R\x0eoriginalUnitId\"?\n" +
	"\x13StorageArtifactData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\"i\n" +
	"\x15StorageConsumableData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fbox_contents\x18\x02 \x03(\tR\vboxContents\x12\x19\n" +
	"\bbox_size\x18\x03 \x01(\x05R\aboxSize\"\x8c\x05\n" +
	"\x10StoragePrototype\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12)\n" +
	"\x10creation_sources\x18\x04 \x03(\tR\x0fcreationSources\x12'\n" +
	"\x0festimated_worth\x18\x05 \x01(\x05R\x0eestimatedWorth\x12+\n" +
	"\x11short_description\x18\x06 \x01(\tR\x10shortDescription\x12)\n" +
	"\x10full_description\x18\a \x01(\tR\x0ffullDescription\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\x12<\n" +
	"\tbuff_data\x18\t \x01(\v2\x1d.game.grpc.v1.StorageBuffDataH\x00R\bbuffData\x12?\n" +
	"\n" +
	"intel_data\x18\n" +
	" \x01(\v2\x1e.game.grpc.v1.StorageIntelDataH\x00R\tintelData\x12E\n" +
	"\fdamaged_data\x18\v \x01(\v2 .game.grpc.v1.StorageDamagedDataH\x00R\vdamagedData\x12H\n" +
	"\rartifact_data\x18\f \x01(\v2!.game.grpc.v1.StorageArtifactDataH\x00R\fartifactData\x12N\n" +
	"\x0fconsumable_data\x18\r \x01(\v2#.game.grpc.v1.StorageConsumableDataH\x00R\x0econsumableDataB\x0f\n" +
	"\rcategory_data\"\x1e\n" +
	"\x1cListStoragePrototypesRequest\"_\n" +
	"\x1dListStoragePrototypesResponse\x12>\n" +
	"\n" +
	"prototypes\x18\x01 \x03(\v2\x1e.game.grpc.v1.StoragePrototypeR\n" +
	"prototypes\",\n" +
	"\x1aGetStoragePrototypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"[\n" +
	"\x1bGetStoragePrototypeResponse\x12<\n" +
	"\tprototype\x18\x01 \x01(\v2\x1e.game.grpc.v1.StoragePrototypeR\tprototype\"]\n" +
	"\x1dCreateStoragePrototypeRequest\x12<\n" +
	"\tprototype\x18\x01 \x01(\v2\x1e.game.grpc.v1.StoragePrototypeR\tprototype\"^\n" +
	"\x1eCreateStoragePrototypeResponse\x12<\n" +
	"\tprototype\x18\x01 \x01(\v2\x1e.game.grpc.v1.StoragePrototypeR\tprototype\"]\n" +
	"\x1dUpdateStoragePrototypeRequest\x12<\n" +
	"\tprototype\x18\x01 \x01(\v2\x1e.game.grpc.v1.StoragePrototypeR\tprototype\"^\n" +
	"\x1eUpdateStoragePrototypeResponse\x12<\n" +
	"\tprototype\x18\x01 \x01(\v2\x1e.game.grpc.v1.StoragePrototypeR\tprototype2\xba\x03\n" +
	"\x14ArmyPrototypeService\x12g\n" +
	"\x12ListArmyPrototypes\x12'.game.grpc.v1.ListArmyPrototypesRequest\x1a(.game.grpc.v1.ListArmyPrototypesResponse\x12a\n" +
	"\x10GetArmyPrototype\x12%.game.grpc.v1.GetArmyPrototypeRequest\x1a&.game.grpc.v1.GetArmyPrototypeResponse\x12j\n" +
	"\x13CreateArmyPrototype\x12(.game.grpc.v1.CreateArmyPrototypeRequest\x1a).game.grpc.v1.CreateArmyPrototypeResponse\x12j\n" +
	"\x13UpdateArmyPrototype\x12(.game.grpc.v1.UpdateArmyPrototypeRequest\x1a).game.grpc.v1.UpdateArmyPrototypeResponse2\xc7\x03\n" +
	"\x15BuildPrototypeService\x12j\n" +
	"\x13ListBuildPrototypes\x12(.game.grpc.v1.ListBuildPrototypesRequest\x1a).game.grpc.v1.ListBuildPrototypesResponse\x12d\n" +
	"\x11GetBuildPrototype\x12&.game.grpc.v1.GetBuildPrototypeRequest\x1a'.game.grpc.v1.GetBuildPrototypeResponse\x12m\n" +
	"\x14CreateBuildPrototype\x12).game.grpc.v1.CreateBuildPrototypeRequest\x1a*.game.grpc.v1.CreateBuildPrototypeResponse\x12m\n" +
	"\x14UpdateBuildPrototype\x12).game.grpc.v1.UpdateBuildPrototypeRequest\x1a*.game.grpc.v1.UpdateBuildPrototypeResponse2\xe1\x03\n" +
	"\x17StoragePrototypeService\x12p\n" +
	"\x15ListStoragePrototypes\x12*.game.grpc.v1.ListStoragePrototypesRequest\x1a+.game.grpc.v1.ListStoragePrototypesResponse\x12j\n" +
	"\x13GetStoragePrototype\x12(.game.grpc.v1.GetStoragePrototypeRequest\x1a).game.grpc.v1.GetStoragePrototypeResponse\x12s\n" +
	"\x16CreateStoragePrototype\x12+.game.grpc.v1.CreateStoragePrototypeRequest\x1a,.game.grpc.v1.CreateStoragePrototypeResponse\x12s\n" +
	"\x16UpdateStoragePrototype\x12+.game.grpc.v1.UpdateStoragePrototypeRequest\x1a,.game.grpc.v1.UpdateStoragePrototypeResponseBKZIgithub.com/artcodefun/heat-expansion-server/contracts/game/grpc/v1;gamev1b\x06proto3"

var (
	file_game_grpc_v1_admin_proto_rawDescOnce sync.Once
	file_game_grpc_v1_admin_proto_rawDescData []byte
)

func file_game_grpc_v1_admin_proto_rawDescGZIP() []byte {
	file_game_grpc_v1_admin_proto_rawDescOnce.Do(func() {
		file_game_grpc_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_grpc_v1_admin_proto_rawDesc), len(file_game_grpc_v1_admin_proto_rawDesc)))
	})
	return file_game_grpc_v1_admin_proto_rawDescData
}

var file_game_grpc_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_game_grpc_v1_admin_proto_goTypes = []any{
	(*PriceModel)(nil),                     // 0: game.grpc.v1.PriceModel
	(*ArmyPrototype)(nil),                  // 1: game.grpc.v1.ArmyPrototype
	(*ListArmyPrototypesRequest)(nil),      // 2: game.grpc.v1.ListArmyPrototypesRequest
	(*ListArmyPrototypesResponse)(nil),     // 3: game.grpc.v1.ListArmyPrototypesResponse
	(*GetArmyPrototypeRequest)(nil),        // 4: game.grpc.v1.GetArmyPrototypeRequest
	(*GetArmyPrototypeResponse)(nil),       // 5: game.grpc.v1.GetArmyPrototypeResponse
	(*CreateArmyPrototypeRequest)(nil),     // 6: game.grpc.v1.CreateArmyPrototypeRequest
	(*CreateArmyPrototypeResponse)(nil),    // 7: game.grpc.v1.CreateArmyPrototypeResponse
	(*UpdateArmyPrototypeRequest)(nil),     // 8: game.grpc.v1.UpdateArmyPrototypeRequest
	(*UpdateArmyPrototypeResponse)(nil),    // 9: game.grpc.v1.UpdateArmyPrototypeResponse
	(*BuildControlData)(nil),               // 10: game.grpc.v1.BuildControlData
	(*BuildResourcesData)(nil),             // 11: game.grpc.v1.BuildResourcesData
	(*BuildDefenseData)(nil),               // 12: game.grpc.v1.BuildDefenseData
	(*BuildMilitaryData)(nil),              // 13: game.grpc.v1.BuildMilitaryData
	(*BuildIntelligenceData)(nil),          // 14: game.grpc.v1.BuildIntelligenceData
	(*BuildPrototype)(nil),                 // 15: game.grpc.v1.BuildPrototype
	(*ListBuildPrototypesRequest)(nil),     // 16: game.grpc.v1.ListBuildPrototypesRequest
	(*ListBuildPrototypesResponse)(nil),    // 17: game.grpc.v1.ListBuildPrototypesResponse
	(*GetBuildPrototypeRequest)(nil),       // 18: game.grpc.v1.GetBuildPrototypeRequest
	(*GetBuildPrototypeResponse)(nil),      // 19: game.grpc.v1.GetBuildPrototypeResponse
	(*CreateBuildPrototypeRequest)(nil),    // 20: game.grpc.v1.CreateBuildPrototypeRequest
	(*CreateBuildPrototypeResponse)(nil),   // 21: game.grpc.v1.CreateBuildPrototypeResponse
	(*UpdateBuildPrototypeRequest)(nil),    // 22: game.grpc.v1.UpdateBuildPrototypeRequest
	(*UpdateBuildPrototypeResponse)(nil),   // 23: game.grpc.v1.UpdateBuildPrototypeResponse
	(*StorageBuffData)(nil),                // 24: game.grpc.v1.StorageBuffData
	(*StorageIntelData)(nil),               // 25: game.grpc.v1.StorageIntelData
	(*StorageDamagedData)(nil),             // 26: game.grpc.v1.StorageDamagedData
	(*StorageArtifactData)(nil),            // 27: game.grpc.v1.StorageArtifactData
	(*StorageConsumableData)(nil),          // 28: game.grpc.v1.StorageConsumableData
	(*StoragePrototype)(nil),               // 29: game.grpc.v1.StoragePrototype
	(*ListStoragePrototypesRequest)(nil),   // 30: game.grpc.v1.ListStoragePrototypesRequest
	(*ListStoragePrototypesResponse)(nil),  // 31: game.grpc.v1.ListStoragePrototypesResponse
	(*GetStoragePrototypeRequest)(nil),     // 32: game.grpc.v1.GetStoragePrototypeRequest
	(*GetStoragePrototypeResponse)(nil),    // 33: game.grpc.v1.GetStoragePrototypeResponse
	(*CreateStoragePrototypeRequest)(nil),  // 34: game.grpc.v1.CreateStoragePrototypeRequest
	(*CreateStoragePrototypeResponse)(nil), // 35: game.grpc.v1.CreateStoragePrototypeResponse
	(*UpdateStoragePrototypeRequest)(nil),  // 36: game.grpc.v1.UpdateStoragePrototypeRequest
	(*UpdateStoragePrototypeResponse)(nil), // 37: game.grpc.v1.UpdateStoragePrototypeResponse
}
var file_game_grpc_v1_admin_proto_depIdxs = []int32{
	0,  // 0: game.grpc.v1.ArmyPrototype.price:type_name -> game.grpc.v1.PriceModel
	1,  // 1: game.grpc.v1.ListArmyPrototypesResponse.prototypes:type_name -> game.grpc.v1.ArmyPrototype
	1,  // 2: game.grpc.v1.GetArmyPrototypeResponse.prototype:type_name -> game.grpc.v1.ArmyPrototype
	1,  // 3: game.grpc.v1.CreateArmyPrototypeRequest.prototype:type_name -> game.grpc.v1.ArmyPrototype
	1,  // 4: game.grpc.v1.CreateArmyPrototypeResponse.prototype:type_name -> game.grpc.v1.ArmyPrototype
	1,  // 5: game.grpc.v1.UpdateArmyPrototypeRequest.prototype:type_name -> game.grpc.v1.ArmyPrototype
	1,  // 6: game.grpc.v1.UpdateArmyPrototypeResponse.prototype:type_name -> game.grpc.v1.ArmyPrototype
	0,  // 7: game.grpc.v1.BuildPrototype.price:type_name -> game.grpc.v1.PriceModel
	10, // 8: game.grpc.v1.BuildPrototype.control_data:type_name -> game.grpc.v1.BuildControlData
	11, // 9: game.grpc.v1.BuildPrototype.resources_data:type_name -> game.grpc.v1.BuildResourcesData
	12, // 10: game.grpc.v1.BuildPrototype.defense_data:type_name -> game.grpc.v1.BuildDefenseData
	13, // 11: game.grpc.v1.BuildPrototype.military_data:type_name -> game.grpc.v1.BuildMilitaryData
	14, // 12: game.grpc.v1.BuildPrototype.intelligence_data:type_name -> game.grpc.v1.BuildIntelligenceData
	15, // 13: game.grpc.v1.ListBuildPrototypesResponse.prototypes:type_name -> game.grpc.v1.BuildPrototype
	15, // 14: game.grpc.v1.GetBuildPrototypeResponse.prototype:type_name -> game.grpc.v1.BuildPrototype
	15, // 15: game.grpc.v1.CreateBuildPrototypeRequest.prototype:type_name -> game.grpc.v1.BuildPrototype
	15, // 16: game.grpc.v1.CreateBuildPrototypeResponse.prototype:type_name -> game.grpc.v1.BuildPrototype
	15, // 17: game.grpc.v1.UpdateBuildPrototypeRequest.prototype:type_name -> game.grpc.v1.BuildPrototype
	15, // 18: game.grpc.v1.UpdateBuildPrototypeResponse.prototype:type_name -> game.grpc.v1.BuildPrototype
	0,  // 19: game.grpc.v1.StorageDamagedData.restore_price:type_name -> game.grpc.v1.PriceModel
	24, // 20: game.grpc.v1.StoragePrototype.buff_data:type_name -> game.grpc.v1.StorageBuffData
	25, // 21: game.grpc.v1.StoragePrototype.intel_data:type_name -> game.grpc.v1.StorageIntelData
	26, // 22: game.grpc.v1.StoragePrototype.damaged_data:type_name -> game.grpc.v1.StorageDamagedData
	27, // 23: game.grpc.v1.StoragePrototype.artifact_data:type_name -> game.grpc.v1.StorageArtifactData
	28, // 24: game.grpc.v1.StoragePrototype.consumable_data:type_name -> game.grpc.v1.StorageConsumableData
	29, // 25: game.grpc.v1.ListStoragePrototypesResponse.prototypes:type_name -> game.grpc.v1.StoragePrototype
	29, // 26: game.grpc.v1.GetStoragePrototypeResponse.prototype:type_name -> game.grpc.v1.StoragePrototype
	29, // 27: game.grpc.v1.CreateStoragePrototypeRequest.prototype:type_name -> game.grpc.v1.StoragePrototype
	29, // 28: game.grpc.v1.CreateStoragePrototypeResponse.prototype:type_name -> game.grpc.v1.StoragePrototype
	29, // 29: game.grpc.v1.UpdateStoragePrototypeRequest.prototype:type_name -> game.grpc.v1.StoragePrototype
	29, // 30: game.grpc.v1.UpdateStoragePrototypeResponse.prototype:type_name -> game.grpc.v1.StoragePrototype
	2,  // 31: game.grpc.v1.ArmyPrototypeService.ListArmyPrototypes:input_type -> game.grpc.v1.ListArmyPrototypesRequest
	4,  // 32: game.grpc.v1.ArmyPrototypeService.GetArmyPrototype:input_type -> game.grpc.v1.GetArmyPrototypeRequest
	6,  // 33: game.grpc.v1.ArmyPrototypeService.CreateArmyPrototype:input_type -> game.grpc.v1.CreateArmyPrototypeRequest
	8,  // 34: game.grpc.v1.ArmyPrototypeService.UpdateArmyPrototype:input_type -> game.grpc.v1.UpdateArmyPrototypeRequest
	16, // 35: game.grpc.v1.BuildPrototypeService.ListBuildPrototypes:input_type -> game.grpc.v1.ListBuildPrototypesRequest
	18, // 36: game.grpc.v1.BuildPrototypeService.GetBuildPrototype:input_type -> game.grpc.v1.GetBuildPrototypeRequest
	20, // 37: game.grpc.v1.BuildPrototypeService.CreateBuildPrototype:input_type -> game.grpc.v1.CreateBuildPrototypeRequest
	22, // 38: game.grpc.v1.BuildPrototypeService.UpdateBuildPrototype:input_type -> game.grpc.v1.UpdateBuildPrototypeRequest
	30, // 39: game.grpc.v1.StoragePrototypeService.ListStoragePrototypes:input_type -> game.grpc.v1.ListStoragePrototypesRequest
	32, // 40: game.grpc.v1.StoragePrototypeService.GetStoragePrototype:input_type -> game.grpc.v1.GetStoragePrototypeRequest
	34, // 41: game.grpc.v1.StoragePrototypeService.CreateStoragePrototype:input_type -> game.grpc.v1.CreateStoragePrototypeRequest
	36, // 42: game.grpc.v1.StoragePrototypeService.UpdateStoragePrototype:input_type -> game.grpc.v1.UpdateStoragePrototypeRequest
	3,  // 43: game.grpc.v1.ArmyPrototypeService.ListArmyPrototypes:output_type -> game.grpc.v1.ListArmyPrototypesResponse
	5,  // 44: game.grpc.v1.ArmyPrototypeService.GetArmyPrototype:output_type -> game.grpc.v1.GetArmyPrototypeResponse
	7,  // 45: game.grpc.v1.ArmyPrototypeService.CreateArmyPrototype:output_type -> game.grpc.v1.CreateArmyPrototypeResponse
	9,  // 46: game.grpc.v1.ArmyPrototypeService.UpdateArmyPrototype:output_type -> game.grpc.v1.UpdateArmyPrototypeResponse
	17, // 47: game.grpc.v1.BuildPrototypeService.ListBuildPrototypes:output_type -> game.grpc.v1.ListBuildPrototypesResponse
	19, // 48: game.grpc.v1.BuildPrototypeService.GetBuildPrototype:output_type -> game.grpc.v1.GetBuildPrototypeResponse
	21, // 49: game.grpc.v1.BuildPrototypeService.CreateBuildPrototype:output_type -> game.grpc.v1.CreateBuildPrototypeResponse
	23, // 50: game.grpc.v1.BuildPrototypeService.UpdateBuildPrototype:output_type -> game.grpc.v1.UpdateBuildPrototypeResponse
	31, // 51: game.grpc.v1.StoragePrototypeService.ListStoragePrototypes:output_type -> game.grpc.v1.ListStoragePrototypesResponse
	33, // 52: game.grpc.v1.StoragePrototypeService.GetStoragePrototype:output_type -> game.grpc.v1.GetStoragePrototypeResponse
	35, // 53: game.grpc.v1.StoragePrototypeService.CreateStoragePrototype:output_type -> game.grpc.v1.CreateStoragePrototypeResponse
	37, // 54: game.grpc.v1.StoragePrototypeService.UpdateStoragePrototype:output_type -> game.grpc.v1.UpdateStoragePrototypeResponse
	43, // [43:55] is the sub-list for method output_type
	31, // [31:43] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_game_grpc_v1_admin_proto_init() }
func file_game_grpc_v1_admin_proto_init() {
	if File_game_grpc_v1_admin_proto != nil {
		return
	}
	file_game_grpc_v1_admin_proto_msgTypes[1].OneofWrappers = []any{}
	file_game_grpc_v1_admin_proto_msgTypes[15].OneofWrappers = []any{
		(*BuildPrototype_ControlData)(nil),
		(*BuildPrototype_ResourcesData)(nil),
		(*BuildPrototype_DefenseData)(nil),
		(*BuildPrototype_MilitaryData)(nil),
		(*BuildPrototype_IntelligenceData)(nil),
	}
	file_game_grpc_v1_admin_proto_msgTypes[29].OneofWrappers = []any{
		(*StoragePrototype_BuffData)(nil),
		(*StoragePrototype_IntelData)(nil),
		(*StoragePrototype_DamagedData)(nil),
		(*StoragePrototype_ArtifactData)(nil),
		(*StoragePrototype_ConsumableData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_grpc_v1_admin_proto_rawDesc), len(file_game_grpc_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_game_grpc_v1_admin_proto_goTypes,
		DependencyIndexes: file_game_grpc_v1_admin_proto_depIdxs,
		MessageInfos:      file_game_grpc_v1_admin_proto_msgTypes,
	}.Build()
	File_game_grpc_v1_admin_proto = out.File
	file_game_grpc_v1_admin_proto_goTypes = nil
	file_game_grpc_v1_admin_proto_depIdxs = nil
}
