// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: game/grpc/v1/admin.proto

package gamev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArmyPrototypeService_ListArmyPrototypes_FullMethodName  = "/game.grpc.v1.ArmyPrototypeService/ListArmyPrototypes"
	ArmyPrototypeService_GetArmyPrototype_FullMethodName    = "/game.grpc.v1.ArmyPrototypeService/GetArmyPrototype"
	ArmyPrototypeService_CreateArmyPrototype_FullMethodName = "/game.grpc.v1.ArmyPrototypeService/CreateArmyPrototype"
	ArmyPrototypeService_UpdateArmyPrototype_FullMethodName = "/game.grpc.v1.ArmyPrototypeService/UpdateArmyPrototype"
)

// ArmyPrototypeServiceClient is the client API for ArmyPrototypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArmyPrototypeServiceClient interface {
	ListArmyPrototypes(ctx context.Context, in *ListArmyPrototypesRequest, opts ...grpc.CallOption) (*ListArmyPrototypesResponse, error)
	GetArmyPrototype(ctx context.Context, in *GetArmyPrototypeRequest, opts ...grpc.CallOption) (*GetArmyPrototypeResponse, error)
	CreateArmyPrototype(ctx context.Context, in *CreateArmyPrototypeRequest, opts ...grpc.CallOption) (*CreateArmyPrototypeResponse, error)
	UpdateArmyPrototype(ctx context.Context, in *UpdateArmyPrototypeRequest, opts ...grpc.CallOption) (*UpdateArmyPrototypeResponse, error)
}

type armyPrototypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArmyPrototypeServiceClient(cc grpc.ClientConnInterface) ArmyPrototypeServiceClient {
	return &armyPrototypeServiceClient{cc}
}

func (c *armyPrototypeServiceClient) ListArmyPrototypes(ctx context.Context, in *ListArmyPrototypesRequest, opts ...grpc.CallOption) (*ListArmyPrototypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArmyPrototypesResponse)
	err := c.cc.Invoke(ctx, ArmyPrototypeService_ListArmyPrototypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armyPrototypeServiceClient) GetArmyPrototype(ctx context.Context, in *GetArmyPrototypeRequest, opts ...grpc.CallOption) (*GetArmyPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArmyPrototypeResponse)
	err := c.cc.Invoke(ctx, ArmyPrototypeService_GetArmyPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armyPrototypeServiceClient) CreateArmyPrototype(ctx context.Context, in *CreateArmyPrototypeRequest, opts ...grpc.CallOption) (*CreateArmyPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArmyPrototypeResponse)
	err := c.cc.Invoke(ctx, ArmyPrototypeService_CreateArmyPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armyPrototypeServiceClient) UpdateArmyPrototype(ctx context.Context, in *UpdateArmyPrototypeRequest, opts ...grpc.CallOption) (*UpdateArmyPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArmyPrototypeResponse)
	err := c.cc.Invoke(ctx, ArmyPrototypeService_UpdateArmyPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArmyPrototypeServiceServer is the server API for ArmyPrototypeService service.
// All implementations must embed UnimplementedArmyPrototypeServiceServer
// for forward compatibility.
type ArmyPrototypeServiceServer interface {
	ListArmyPrototypes(context.Context, *ListArmyPrototypesRequest) (*ListArmyPrototypesResponse, error)
	GetArmyPrototype(context.Context, *GetArmyPrototypeRequest) (*GetArmyPrototypeResponse, error)
	CreateArmyPrototype(context.Context, *CreateArmyPrototypeRequest) (*CreateArmyPrototypeResponse, error)
	UpdateArmyPrototype(context.Context, *UpdateArmyPrototypeRequest) (*UpdateArmyPrototypeResponse, error)
	mustEmbedUnimplementedArmyPrototypeServiceServer()
}

// UnimplementedArmyPrototypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArmyPrototypeServiceServer struct{}

func (UnimplementedArmyPrototypeServiceServer) ListArmyPrototypes(context.Context, *ListArmyPrototypesRequest) (*ListArmyPrototypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArmyPrototypes not implemented")
}
func (UnimplementedArmyPrototypeServiceServer) GetArmyPrototype(context.Context, *GetArmyPrototypeRequest) (*GetArmyPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArmyPrototype not implemented")
}
func (UnimplementedArmyPrototypeServiceServer) CreateArmyPrototype(context.Context, *CreateArmyPrototypeRequest) (*CreateArmyPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArmyPrototype not implemented")
}
func (UnimplementedArmyPrototypeServiceServer) UpdateArmyPrototype(context.Context, *UpdateArmyPrototypeRequest) (*UpdateArmyPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArmyPrototype not implemented")
}
func (UnimplementedArmyPrototypeServiceServer) mustEmbedUnimplementedArmyPrototypeServiceServer() {}
func (UnimplementedArmyPrototypeServiceServer) testEmbeddedByValue()                              {}

// UnsafeArmyPrototypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArmyPrototypeServiceServer will
// result in compilation errors.
type UnsafeArmyPrototypeServiceServer interface {
	mustEmbedUnimplementedArmyPrototypeServiceServer()
}

func RegisterArmyPrototypeServiceServer(s grpc.ServiceRegistrar, srv ArmyPrototypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedArmyPrototypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArmyPrototypeService_ServiceDesc, srv)
}

func _ArmyPrototypeService_ListArmyPrototypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArmyPrototypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmyPrototypeServiceServer).ListArmyPrototypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmyPrototypeService_ListArmyPrototypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmyPrototypeServiceServer).ListArmyPrototypes(ctx, req.(*ListArmyPrototypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArmyPrototypeService_GetArmyPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArmyPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmyPrototypeServiceServer).GetArmyPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmyPrototypeService_GetArmyPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmyPrototypeServiceServer).GetArmyPrototype(ctx, req.(*GetArmyPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArmyPrototypeService_CreateArmyPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArmyPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmyPrototypeServiceServer).CreateArmyPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmyPrototypeService_CreateArmyPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmyPrototypeServiceServer).CreateArmyPrototype(ctx, req.(*CreateArmyPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArmyPrototypeService_UpdateArmyPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArmyPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmyPrototypeServiceServer).UpdateArmyPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmyPrototypeService_UpdateArmyPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmyPrototypeServiceServer).UpdateArmyPrototype(ctx, req.(*UpdateArmyPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArmyPrototypeService_ServiceDesc is the grpc.ServiceDesc for ArmyPrototypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArmyPrototypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.grpc.v1.ArmyPrototypeService",
	HandlerType: (*ArmyPrototypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListArmyPrototypes",
			Handler:    _ArmyPrototypeService_ListArmyPrototypes_Handler,
		},
		{
			MethodName: "GetArmyPrototype",
			Handler:    _ArmyPrototypeService_GetArmyPrototype_Handler,
		},
		{
			MethodName: "CreateArmyPrototype",
			Handler:    _ArmyPrototypeService_CreateArmyPrototype_Handler,
		},
		{
			MethodName: "UpdateArmyPrototype",
			Handler:    _ArmyPrototypeService_UpdateArmyPrototype_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game/grpc/v1/admin.proto",
}
