// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: game/grpc/v1/admin.proto

package gamev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArmyPrototypeService_ListArmyPrototypes_FullMethodName  = "/game.grpc.v1.ArmyPrototypeService/ListArmyPrototypes"
	ArmyPrototypeService_GetArmyPrototype_FullMethodName    = "/game.grpc.v1.ArmyPrototypeService/GetArmyPrototype"
	ArmyPrototypeService_CreateArmyPrototype_FullMethodName = "/game.grpc.v1.ArmyPrototypeService/CreateArmyPrototype"
	ArmyPrototypeService_UpdateArmyPrototype_FullMethodName = "/game.grpc.v1.ArmyPrototypeService/UpdateArmyPrototype"
)

// ArmyPrototypeServiceClient is the client API for ArmyPrototypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArmyPrototypeServiceClient interface {
	ListArmyPrototypes(ctx context.Context, in *ListArmyPrototypesRequest, opts ...grpc.CallOption) (*ListArmyPrototypesResponse, error)
	GetArmyPrototype(ctx context.Context, in *GetArmyPrototypeRequest, opts ...grpc.CallOption) (*GetArmyPrototypeResponse, error)
	CreateArmyPrototype(ctx context.Context, in *CreateArmyPrototypeRequest, opts ...grpc.CallOption) (*CreateArmyPrototypeResponse, error)
	UpdateArmyPrototype(ctx context.Context, in *UpdateArmyPrototypeRequest, opts ...grpc.CallOption) (*UpdateArmyPrototypeResponse, error)
}

type armyPrototypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArmyPrototypeServiceClient(cc grpc.ClientConnInterface) ArmyPrototypeServiceClient {
	return &armyPrototypeServiceClient{cc}
}

func (c *armyPrototypeServiceClient) ListArmyPrototypes(ctx context.Context, in *ListArmyPrototypesRequest, opts ...grpc.CallOption) (*ListArmyPrototypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArmyPrototypesResponse)
	err := c.cc.Invoke(ctx, ArmyPrototypeService_ListArmyPrototypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armyPrototypeServiceClient) GetArmyPrototype(ctx context.Context, in *GetArmyPrototypeRequest, opts ...grpc.CallOption) (*GetArmyPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArmyPrototypeResponse)
	err := c.cc.Invoke(ctx, ArmyPrototypeService_GetArmyPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armyPrototypeServiceClient) CreateArmyPrototype(ctx context.Context, in *CreateArmyPrototypeRequest, opts ...grpc.CallOption) (*CreateArmyPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArmyPrototypeResponse)
	err := c.cc.Invoke(ctx, ArmyPrototypeService_CreateArmyPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armyPrototypeServiceClient) UpdateArmyPrototype(ctx context.Context, in *UpdateArmyPrototypeRequest, opts ...grpc.CallOption) (*UpdateArmyPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArmyPrototypeResponse)
	err := c.cc.Invoke(ctx, ArmyPrototypeService_UpdateArmyPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArmyPrototypeServiceServer is the server API for ArmyPrototypeService service.
// All implementations must embed UnimplementedArmyPrototypeServiceServer
// for forward compatibility.
type ArmyPrototypeServiceServer interface {
	ListArmyPrototypes(context.Context, *ListArmyPrototypesRequest) (*ListArmyPrototypesResponse, error)
	GetArmyPrototype(context.Context, *GetArmyPrototypeRequest) (*GetArmyPrototypeResponse, error)
	CreateArmyPrototype(context.Context, *CreateArmyPrototypeRequest) (*CreateArmyPrototypeResponse, error)
	UpdateArmyPrototype(context.Context, *UpdateArmyPrototypeRequest) (*UpdateArmyPrototypeResponse, error)
	mustEmbedUnimplementedArmyPrototypeServiceServer()
}

// UnimplementedArmyPrototypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArmyPrototypeServiceServer struct{}

func (UnimplementedArmyPrototypeServiceServer) ListArmyPrototypes(context.Context, *ListArmyPrototypesRequest) (*ListArmyPrototypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArmyPrototypes not implemented")
}
func (UnimplementedArmyPrototypeServiceServer) GetArmyPrototype(context.Context, *GetArmyPrototypeRequest) (*GetArmyPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArmyPrototype not implemented")
}
func (UnimplementedArmyPrototypeServiceServer) CreateArmyPrototype(context.Context, *CreateArmyPrototypeRequest) (*CreateArmyPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArmyPrototype not implemented")
}
func (UnimplementedArmyPrototypeServiceServer) UpdateArmyPrototype(context.Context, *UpdateArmyPrototypeRequest) (*UpdateArmyPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArmyPrototype not implemented")
}
func (UnimplementedArmyPrototypeServiceServer) mustEmbedUnimplementedArmyPrototypeServiceServer() {}
func (UnimplementedArmyPrototypeServiceServer) testEmbeddedByValue()                              {}

// UnsafeArmyPrototypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArmyPrototypeServiceServer will
// result in compilation errors.
type UnsafeArmyPrototypeServiceServer interface {
	mustEmbedUnimplementedArmyPrototypeServiceServer()
}

func RegisterArmyPrototypeServiceServer(s grpc.ServiceRegistrar, srv ArmyPrototypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedArmyPrototypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArmyPrototypeService_ServiceDesc, srv)
}

func _ArmyPrototypeService_ListArmyPrototypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArmyPrototypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmyPrototypeServiceServer).ListArmyPrototypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmyPrototypeService_ListArmyPrototypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmyPrototypeServiceServer).ListArmyPrototypes(ctx, req.(*ListArmyPrototypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArmyPrototypeService_GetArmyPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArmyPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmyPrototypeServiceServer).GetArmyPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmyPrototypeService_GetArmyPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmyPrototypeServiceServer).GetArmyPrototype(ctx, req.(*GetArmyPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArmyPrototypeService_CreateArmyPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArmyPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmyPrototypeServiceServer).CreateArmyPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmyPrototypeService_CreateArmyPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmyPrototypeServiceServer).CreateArmyPrototype(ctx, req.(*CreateArmyPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArmyPrototypeService_UpdateArmyPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArmyPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmyPrototypeServiceServer).UpdateArmyPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArmyPrototypeService_UpdateArmyPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmyPrototypeServiceServer).UpdateArmyPrototype(ctx, req.(*UpdateArmyPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArmyPrototypeService_ServiceDesc is the grpc.ServiceDesc for ArmyPrototypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArmyPrototypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.grpc.v1.ArmyPrototypeService",
	HandlerType: (*ArmyPrototypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListArmyPrototypes",
			Handler:    _ArmyPrototypeService_ListArmyPrototypes_Handler,
		},
		{
			MethodName: "GetArmyPrototype",
			Handler:    _ArmyPrototypeService_GetArmyPrototype_Handler,
		},
		{
			MethodName: "CreateArmyPrototype",
			Handler:    _ArmyPrototypeService_CreateArmyPrototype_Handler,
		},
		{
			MethodName: "UpdateArmyPrototype",
			Handler:    _ArmyPrototypeService_UpdateArmyPrototype_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game/grpc/v1/admin.proto",
}

const (
	BuildPrototypeService_ListBuildPrototypes_FullMethodName  = "/game.grpc.v1.BuildPrototypeService/ListBuildPrototypes"
	BuildPrototypeService_GetBuildPrototype_FullMethodName    = "/game.grpc.v1.BuildPrototypeService/GetBuildPrototype"
	BuildPrototypeService_CreateBuildPrototype_FullMethodName = "/game.grpc.v1.BuildPrototypeService/CreateBuildPrototype"
	BuildPrototypeService_UpdateBuildPrototype_FullMethodName = "/game.grpc.v1.BuildPrototypeService/UpdateBuildPrototype"
)

// BuildPrototypeServiceClient is the client API for BuildPrototypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuildPrototypeServiceClient interface {
	ListBuildPrototypes(ctx context.Context, in *ListBuildPrototypesRequest, opts ...grpc.CallOption) (*ListBuildPrototypesResponse, error)
	GetBuildPrototype(ctx context.Context, in *GetBuildPrototypeRequest, opts ...grpc.CallOption) (*GetBuildPrototypeResponse, error)
	CreateBuildPrototype(ctx context.Context, in *CreateBuildPrototypeRequest, opts ...grpc.CallOption) (*CreateBuildPrototypeResponse, error)
	UpdateBuildPrototype(ctx context.Context, in *UpdateBuildPrototypeRequest, opts ...grpc.CallOption) (*UpdateBuildPrototypeResponse, error)
}

type buildPrototypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildPrototypeServiceClient(cc grpc.ClientConnInterface) BuildPrototypeServiceClient {
	return &buildPrototypeServiceClient{cc}
}

func (c *buildPrototypeServiceClient) ListBuildPrototypes(ctx context.Context, in *ListBuildPrototypesRequest, opts ...grpc.CallOption) (*ListBuildPrototypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBuildPrototypesResponse)
	err := c.cc.Invoke(ctx, BuildPrototypeService_ListBuildPrototypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildPrototypeServiceClient) GetBuildPrototype(ctx context.Context, in *GetBuildPrototypeRequest, opts ...grpc.CallOption) (*GetBuildPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBuildPrototypeResponse)
	err := c.cc.Invoke(ctx, BuildPrototypeService_GetBuildPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildPrototypeServiceClient) CreateBuildPrototype(ctx context.Context, in *CreateBuildPrototypeRequest, opts ...grpc.CallOption) (*CreateBuildPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBuildPrototypeResponse)
	err := c.cc.Invoke(ctx, BuildPrototypeService_CreateBuildPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildPrototypeServiceClient) UpdateBuildPrototype(ctx context.Context, in *UpdateBuildPrototypeRequest, opts ...grpc.CallOption) (*UpdateBuildPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBuildPrototypeResponse)
	err := c.cc.Invoke(ctx, BuildPrototypeService_UpdateBuildPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildPrototypeServiceServer is the server API for BuildPrototypeService service.
// All implementations must embed UnimplementedBuildPrototypeServiceServer
// for forward compatibility.
type BuildPrototypeServiceServer interface {
	ListBuildPrototypes(context.Context, *ListBuildPrototypesRequest) (*ListBuildPrototypesResponse, error)
	GetBuildPrototype(context.Context, *GetBuildPrototypeRequest) (*GetBuildPrototypeResponse, error)
	CreateBuildPrototype(context.Context, *CreateBuildPrototypeRequest) (*CreateBuildPrototypeResponse, error)
	UpdateBuildPrototype(context.Context, *UpdateBuildPrototypeRequest) (*UpdateBuildPrototypeResponse, error)
	mustEmbedUnimplementedBuildPrototypeServiceServer()
}

// UnimplementedBuildPrototypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildPrototypeServiceServer struct{}

func (UnimplementedBuildPrototypeServiceServer) ListBuildPrototypes(context.Context, *ListBuildPrototypesRequest) (*ListBuildPrototypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBuildPrototypes not implemented")
}
func (UnimplementedBuildPrototypeServiceServer) GetBuildPrototype(context.Context, *GetBuildPrototypeRequest) (*GetBuildPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuildPrototype not implemented")
}
func (UnimplementedBuildPrototypeServiceServer) CreateBuildPrototype(context.Context, *CreateBuildPrototypeRequest) (*CreateBuildPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBuildPrototype not implemented")
}
func (UnimplementedBuildPrototypeServiceServer) UpdateBuildPrototype(context.Context, *UpdateBuildPrototypeRequest) (*UpdateBuildPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBuildPrototype not implemented")
}
func (UnimplementedBuildPrototypeServiceServer) mustEmbedUnimplementedBuildPrototypeServiceServer() {}
func (UnimplementedBuildPrototypeServiceServer) testEmbeddedByValue()                               {}

// UnsafeBuildPrototypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildPrototypeServiceServer will
// result in compilation errors.
type UnsafeBuildPrototypeServiceServer interface {
	mustEmbedUnimplementedBuildPrototypeServiceServer()
}

func RegisterBuildPrototypeServiceServer(s grpc.ServiceRegistrar, srv BuildPrototypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedBuildPrototypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildPrototypeService_ServiceDesc, srv)
}

func _BuildPrototypeService_ListBuildPrototypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuildPrototypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildPrototypeServiceServer).ListBuildPrototypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildPrototypeService_ListBuildPrototypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildPrototypeServiceServer).ListBuildPrototypes(ctx, req.(*ListBuildPrototypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildPrototypeService_GetBuildPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildPrototypeServiceServer).GetBuildPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildPrototypeService_GetBuildPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildPrototypeServiceServer).GetBuildPrototype(ctx, req.(*GetBuildPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildPrototypeService_CreateBuildPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBuildPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildPrototypeServiceServer).CreateBuildPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildPrototypeService_CreateBuildPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildPrototypeServiceServer).CreateBuildPrototype(ctx, req.(*CreateBuildPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildPrototypeService_UpdateBuildPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBuildPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildPrototypeServiceServer).UpdateBuildPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildPrototypeService_UpdateBuildPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildPrototypeServiceServer).UpdateBuildPrototype(ctx, req.(*UpdateBuildPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildPrototypeService_ServiceDesc is the grpc.ServiceDesc for BuildPrototypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildPrototypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.grpc.v1.BuildPrototypeService",
	HandlerType: (*BuildPrototypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBuildPrototypes",
			Handler:    _BuildPrototypeService_ListBuildPrototypes_Handler,
		},
		{
			MethodName: "GetBuildPrototype",
			Handler:    _BuildPrototypeService_GetBuildPrototype_Handler,
		},
		{
			MethodName: "CreateBuildPrototype",
			Handler:    _BuildPrototypeService_CreateBuildPrototype_Handler,
		},
		{
			MethodName: "UpdateBuildPrototype",
			Handler:    _BuildPrototypeService_UpdateBuildPrototype_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game/grpc/v1/admin.proto",
}

const (
	StoragePrototypeService_ListStoragePrototypes_FullMethodName  = "/game.grpc.v1.StoragePrototypeService/ListStoragePrototypes"
	StoragePrototypeService_GetStoragePrototype_FullMethodName    = "/game.grpc.v1.StoragePrototypeService/GetStoragePrototype"
	StoragePrototypeService_CreateStoragePrototype_FullMethodName = "/game.grpc.v1.StoragePrototypeService/CreateStoragePrototype"
	StoragePrototypeService_UpdateStoragePrototype_FullMethodName = "/game.grpc.v1.StoragePrototypeService/UpdateStoragePrototype"
)

// StoragePrototypeServiceClient is the client API for StoragePrototypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoragePrototypeServiceClient interface {
	ListStoragePrototypes(ctx context.Context, in *ListStoragePrototypesRequest, opts ...grpc.CallOption) (*ListStoragePrototypesResponse, error)
	GetStoragePrototype(ctx context.Context, in *GetStoragePrototypeRequest, opts ...grpc.CallOption) (*GetStoragePrototypeResponse, error)
	CreateStoragePrototype(ctx context.Context, in *CreateStoragePrototypeRequest, opts ...grpc.CallOption) (*CreateStoragePrototypeResponse, error)
	UpdateStoragePrototype(ctx context.Context, in *UpdateStoragePrototypeRequest, opts ...grpc.CallOption) (*UpdateStoragePrototypeResponse, error)
}

type storagePrototypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoragePrototypeServiceClient(cc grpc.ClientConnInterface) StoragePrototypeServiceClient {
	return &storagePrototypeServiceClient{cc}
}

func (c *storagePrototypeServiceClient) ListStoragePrototypes(ctx context.Context, in *ListStoragePrototypesRequest, opts ...grpc.CallOption) (*ListStoragePrototypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStoragePrototypesResponse)
	err := c.cc.Invoke(ctx, StoragePrototypeService_ListStoragePrototypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePrototypeServiceClient) GetStoragePrototype(ctx context.Context, in *GetStoragePrototypeRequest, opts ...grpc.CallOption) (*GetStoragePrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStoragePrototypeResponse)
	err := c.cc.Invoke(ctx, StoragePrototypeService_GetStoragePrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePrototypeServiceClient) CreateStoragePrototype(ctx context.Context, in *CreateStoragePrototypeRequest, opts ...grpc.CallOption) (*CreateStoragePrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStoragePrototypeResponse)
	err := c.cc.Invoke(ctx, StoragePrototypeService_CreateStoragePrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePrototypeServiceClient) UpdateStoragePrototype(ctx context.Context, in *UpdateStoragePrototypeRequest, opts ...grpc.CallOption) (*UpdateStoragePrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStoragePrototypeResponse)
	err := c.cc.Invoke(ctx, StoragePrototypeService_UpdateStoragePrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoragePrototypeServiceServer is the server API for StoragePrototypeService service.
// All implementations must embed UnimplementedStoragePrototypeServiceServer
// for forward compatibility.
type StoragePrototypeServiceServer interface {
	ListStoragePrototypes(context.Context, *ListStoragePrototypesRequest) (*ListStoragePrototypesResponse, error)
	GetStoragePrototype(context.Context, *GetStoragePrototypeRequest) (*GetStoragePrototypeResponse, error)
	CreateStoragePrototype(context.Context, *CreateStoragePrototypeRequest) (*CreateStoragePrototypeResponse, error)
	UpdateStoragePrototype(context.Context, *UpdateStoragePrototypeRequest) (*UpdateStoragePrototypeResponse, error)
	mustEmbedUnimplementedStoragePrototypeServiceServer()
}

// UnimplementedStoragePrototypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoragePrototypeServiceServer struct{}

func (UnimplementedStoragePrototypeServiceServer) ListStoragePrototypes(context.Context, *ListStoragePrototypesRequest) (*ListStoragePrototypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStoragePrototypes not implemented")
}
func (UnimplementedStoragePrototypeServiceServer) GetStoragePrototype(context.Context, *GetStoragePrototypeRequest) (*GetStoragePrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStoragePrototype not implemented")
}
func (UnimplementedStoragePrototypeServiceServer) CreateStoragePrototype(context.Context, *CreateStoragePrototypeRequest) (*CreateStoragePrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStoragePrototype not implemented")
}
func (UnimplementedStoragePrototypeServiceServer) UpdateStoragePrototype(context.Context, *UpdateStoragePrototypeRequest) (*UpdateStoragePrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStoragePrototype not implemented")
}
func (UnimplementedStoragePrototypeServiceServer) mustEmbedUnimplementedStoragePrototypeServiceServer() {
}
func (UnimplementedStoragePrototypeServiceServer) testEmbeddedByValue() {}

// UnsafeStoragePrototypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoragePrototypeServiceServer will
// result in compilation errors.
type UnsafeStoragePrototypeServiceServer interface {
	mustEmbedUnimplementedStoragePrototypeServiceServer()
}

func RegisterStoragePrototypeServiceServer(s grpc.ServiceRegistrar, srv StoragePrototypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedStoragePrototypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoragePrototypeService_ServiceDesc, srv)
}

func _StoragePrototypeService_ListStoragePrototypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoragePrototypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePrototypeServiceServer).ListStoragePrototypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePrototypeService_ListStoragePrototypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePrototypeServiceServer).ListStoragePrototypes(ctx, req.(*ListStoragePrototypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePrototypeService_GetStoragePrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoragePrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePrototypeServiceServer).GetStoragePrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePrototypeService_GetStoragePrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePrototypeServiceServer).GetStoragePrototype(ctx, req.(*GetStoragePrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePrototypeService_CreateStoragePrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoragePrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePrototypeServiceServer).CreateStoragePrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePrototypeService_CreateStoragePrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePrototypeServiceServer).CreateStoragePrototype(ctx, req.(*CreateStoragePrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePrototypeService_UpdateStoragePrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStoragePrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePrototypeServiceServer).UpdateStoragePrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePrototypeService_UpdateStoragePrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePrototypeServiceServer).UpdateStoragePrototype(ctx, req.(*UpdateStoragePrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoragePrototypeService_ServiceDesc is the grpc.ServiceDesc for StoragePrototypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoragePrototypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.grpc.v1.StoragePrototypeService",
	HandlerType: (*StoragePrototypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStoragePrototypes",
			Handler:    _StoragePrototypeService_ListStoragePrototypes_Handler,
		},
		{
			MethodName: "GetStoragePrototype",
			Handler:    _StoragePrototypeService_GetStoragePrototype_Handler,
		},
		{
			MethodName: "CreateStoragePrototype",
			Handler:    _StoragePrototypeService_CreateStoragePrototype_Handler,
		},
		{
			MethodName: "UpdateStoragePrototype",
			Handler:    _StoragePrototypeService_UpdateStoragePrototype_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game/grpc/v1/admin.proto",
}

const (
	TechPrototypeService_ListTechPrototypes_FullMethodName  = "/game.grpc.v1.TechPrototypeService/ListTechPrototypes"
	TechPrototypeService_GetTechPrototype_FullMethodName    = "/game.grpc.v1.TechPrototypeService/GetTechPrototype"
	TechPrototypeService_CreateTechPrototype_FullMethodName = "/game.grpc.v1.TechPrototypeService/CreateTechPrototype"
	TechPrototypeService_UpdateTechPrototype_FullMethodName = "/game.grpc.v1.TechPrototypeService/UpdateTechPrototype"
)

// TechPrototypeServiceClient is the client API for TechPrototypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TechPrototypeServiceClient interface {
	ListTechPrototypes(ctx context.Context, in *ListTechPrototypesRequest, opts ...grpc.CallOption) (*ListTechPrototypesResponse, error)
	GetTechPrototype(ctx context.Context, in *GetTechPrototypeRequest, opts ...grpc.CallOption) (*GetTechPrototypeResponse, error)
	CreateTechPrototype(ctx context.Context, in *CreateTechPrototypeRequest, opts ...grpc.CallOption) (*CreateTechPrototypeResponse, error)
	UpdateTechPrototype(ctx context.Context, in *UpdateTechPrototypeRequest, opts ...grpc.CallOption) (*UpdateTechPrototypeResponse, error)
}

type techPrototypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTechPrototypeServiceClient(cc grpc.ClientConnInterface) TechPrototypeServiceClient {
	return &techPrototypeServiceClient{cc}
}

func (c *techPrototypeServiceClient) ListTechPrototypes(ctx context.Context, in *ListTechPrototypesRequest, opts ...grpc.CallOption) (*ListTechPrototypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTechPrototypesResponse)
	err := c.cc.Invoke(ctx, TechPrototypeService_ListTechPrototypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *techPrototypeServiceClient) GetTechPrototype(ctx context.Context, in *GetTechPrototypeRequest, opts ...grpc.CallOption) (*GetTechPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTechPrototypeResponse)
	err := c.cc.Invoke(ctx, TechPrototypeService_GetTechPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *techPrototypeServiceClient) CreateTechPrototype(ctx context.Context, in *CreateTechPrototypeRequest, opts ...grpc.CallOption) (*CreateTechPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTechPrototypeResponse)
	err := c.cc.Invoke(ctx, TechPrototypeService_CreateTechPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *techPrototypeServiceClient) UpdateTechPrototype(ctx context.Context, in *UpdateTechPrototypeRequest, opts ...grpc.CallOption) (*UpdateTechPrototypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTechPrototypeResponse)
	err := c.cc.Invoke(ctx, TechPrototypeService_UpdateTechPrototype_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TechPrototypeServiceServer is the server API for TechPrototypeService service.
// All implementations must embed UnimplementedTechPrototypeServiceServer
// for forward compatibility.
type TechPrototypeServiceServer interface {
	ListTechPrototypes(context.Context, *ListTechPrototypesRequest) (*ListTechPrototypesResponse, error)
	GetTechPrototype(context.Context, *GetTechPrototypeRequest) (*GetTechPrototypeResponse, error)
	CreateTechPrototype(context.Context, *CreateTechPrototypeRequest) (*CreateTechPrototypeResponse, error)
	UpdateTechPrototype(context.Context, *UpdateTechPrototypeRequest) (*UpdateTechPrototypeResponse, error)
	mustEmbedUnimplementedTechPrototypeServiceServer()
}

// UnimplementedTechPrototypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTechPrototypeServiceServer struct{}

func (UnimplementedTechPrototypeServiceServer) ListTechPrototypes(context.Context, *ListTechPrototypesRequest) (*ListTechPrototypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTechPrototypes not implemented")
}
func (UnimplementedTechPrototypeServiceServer) GetTechPrototype(context.Context, *GetTechPrototypeRequest) (*GetTechPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTechPrototype not implemented")
}
func (UnimplementedTechPrototypeServiceServer) CreateTechPrototype(context.Context, *CreateTechPrototypeRequest) (*CreateTechPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTechPrototype not implemented")
}
func (UnimplementedTechPrototypeServiceServer) UpdateTechPrototype(context.Context, *UpdateTechPrototypeRequest) (*UpdateTechPrototypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTechPrototype not implemented")
}
func (UnimplementedTechPrototypeServiceServer) mustEmbedUnimplementedTechPrototypeServiceServer() {}
func (UnimplementedTechPrototypeServiceServer) testEmbeddedByValue()                              {}

// UnsafeTechPrototypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TechPrototypeServiceServer will
// result in compilation errors.
type UnsafeTechPrototypeServiceServer interface {
	mustEmbedUnimplementedTechPrototypeServiceServer()
}

func RegisterTechPrototypeServiceServer(s grpc.ServiceRegistrar, srv TechPrototypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedTechPrototypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TechPrototypeService_ServiceDesc, srv)
}

func _TechPrototypeService_ListTechPrototypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTechPrototypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechPrototypeServiceServer).ListTechPrototypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechPrototypeService_ListTechPrototypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechPrototypeServiceServer).ListTechPrototypes(ctx, req.(*ListTechPrototypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechPrototypeService_GetTechPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTechPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechPrototypeServiceServer).GetTechPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechPrototypeService_GetTechPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechPrototypeServiceServer).GetTechPrototype(ctx, req.(*GetTechPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechPrototypeService_CreateTechPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTechPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechPrototypeServiceServer).CreateTechPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechPrototypeService_CreateTechPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechPrototypeServiceServer).CreateTechPrototype(ctx, req.(*CreateTechPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechPrototypeService_UpdateTechPrototype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTechPrototypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechPrototypeServiceServer).UpdateTechPrototype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechPrototypeService_UpdateTechPrototype_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechPrototypeServiceServer).UpdateTechPrototype(ctx, req.(*UpdateTechPrototypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TechPrototypeService_ServiceDesc is the grpc.ServiceDesc for TechPrototypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TechPrototypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.grpc.v1.TechPrototypeService",
	HandlerType: (*TechPrototypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTechPrototypes",
			Handler:    _TechPrototypeService_ListTechPrototypes_Handler,
		},
		{
			MethodName: "GetTechPrototype",
			Handler:    _TechPrototypeService_GetTechPrototype_Handler,
		},
		{
			MethodName: "CreateTechPrototype",
			Handler:    _TechPrototypeService_CreateTechPrototype_Handler,
		},
		{
			MethodName: "UpdateTechPrototype",
			Handler:    _TechPrototypeService_UpdateTechPrototype_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game/grpc/v1/admin.proto",
}
