// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: game/grpc/v1/admin.proto

package gamev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PriceModel mirrors domain.PriceModel: resource costs in integer minor units.
type PriceModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credits       int64                  `protobuf:"varint,1,opt,name=credits,proto3" json:"credits,omitempty"`
	Iron          int64                  `protobuf:"varint,2,opt,name=iron,proto3" json:"iron,omitempty"`
	Titanium      int64                  `protobuf:"varint,3,opt,name=titanium,proto3" json:"titanium,omitempty"`
	Antimatter    int64                  `protobuf:"varint,4,opt,name=antimatter,proto3" json:"antimatter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceModel) Reset() {
	*x = PriceModel{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceModel) ProtoMessage() {}

func (x *PriceModel) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceModel.ProtoReflect.Descriptor instead.
func (*PriceModel) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *PriceModel) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *PriceModel) GetIron() int64 {
	if x != nil {
		return x.Iron
	}
	return 0
}

func (x *PriceModel) GetTitanium() int64 {
	if x != nil {
		return x.Titanium
	}
	return 0
}

func (x *PriceModel) GetAntimatter() int64 {
	if x != nil {
		return x.Antimatter
	}
	return 0
}

// ArmyPrototype is the wire shape of domain.ArmyItemPrototype.
//
// Enum-like fields (category, faction, creation_sources) are carried as strings
// rather than proto enums: the domain stores them as free string constants and
// the DB is the source of truth, so a parallel proto enum would be a second
// definition that could silently drift. unlock_technology_id is optional
// (absent = available by default).
type ArmyPrototype struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category           string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	CreationSources    []string               `protobuf:"bytes,4,rep,name=creation_sources,json=creationSources,proto3" json:"creation_sources,omitempty"`
	Faction            string                 `protobuf:"bytes,5,opt,name=faction,proto3" json:"faction,omitempty"`
	UnlockTechnologyId *int64                 `protobuf:"varint,6,opt,name=unlock_technology_id,json=unlockTechnologyId,proto3,oneof" json:"unlock_technology_id,omitempty"`
	ShortDescription   string                 `protobuf:"bytes,7,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	FullDescription    string                 `protobuf:"bytes,8,opt,name=full_description,json=fullDescription,proto3" json:"full_description,omitempty"`
	Price              *PriceModel            `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	ProductionTime     int64                  `protobuf:"varint,10,opt,name=production_time,json=productionTime,proto3" json:"production_time,omitempty"`
	Space              int32                  `protobuf:"varint,11,opt,name=space,proto3" json:"space,omitempty"`
	ImageUrl           string                 `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Attack             int32                  `protobuf:"varint,13,opt,name=attack,proto3" json:"attack,omitempty"`
	Defence            int32                  `protobuf:"varint,14,opt,name=defence,proto3" json:"defence,omitempty"`
	Capacity           int32                  `protobuf:"varint,15,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Stealth            int32                  `protobuf:"varint,16,opt,name=stealth,proto3" json:"stealth,omitempty"`
	Speed              int32                  `protobuf:"varint,17,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ArmyPrototype) Reset() {
	*x = ArmyPrototype{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmyPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmyPrototype) ProtoMessage() {}

func (x *ArmyPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmyPrototype.ProtoReflect.Descriptor instead.
func (*ArmyPrototype) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ArmyPrototype) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArmyPrototype) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArmyPrototype) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ArmyPrototype) GetCreationSources() []string {
	if x != nil {
		return x.CreationSources
	}
	return nil
}

func (x *ArmyPrototype) GetFaction() string {
	if x != nil {
		return x.Faction
	}
	return ""
}

func (x *ArmyPrototype) GetUnlockTechnologyId() int64 {
	if x != nil && x.UnlockTechnologyId != nil {
		return *x.UnlockTechnologyId
	}
	return 0
}

func (x *ArmyPrototype) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *ArmyPrototype) GetFullDescription() string {
	if x != nil {
		return x.FullDescription
	}
	return ""
}

func (x *ArmyPrototype) GetPrice() *PriceModel {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *ArmyPrototype) GetProductionTime() int64 {
	if x != nil {
		return x.ProductionTime
	}
	return 0
}

func (x *ArmyPrototype) GetSpace() int32 {
	if x != nil {
		return x.Space
	}
	return 0
}

func (x *ArmyPrototype) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ArmyPrototype) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *ArmyPrototype) GetDefence() int32 {
	if x != nil {
		return x.Defence
	}
	return 0
}

func (x *ArmyPrototype) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ArmyPrototype) GetStealth() int32 {
	if x != nil {
		return x.Stealth
	}
	return 0
}

func (x *ArmyPrototype) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type ListArmyPrototypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArmyPrototypesRequest) Reset() {
	*x = ListArmyPrototypesRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArmyPrototypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArmyPrototypesRequest) ProtoMessage() {}

func (x *ListArmyPrototypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArmyPrototypesRequest.ProtoReflect.Descriptor instead.
func (*ListArmyPrototypesRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{2}
}

type ListArmyPrototypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototypes    []*ArmyPrototype       `protobuf:"bytes,1,rep,name=prototypes,proto3" json:"prototypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArmyPrototypesResponse) Reset() {
	*x = ListArmyPrototypesResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArmyPrototypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArmyPrototypesResponse) ProtoMessage() {}

func (x *ListArmyPrototypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArmyPrototypesResponse.ProtoReflect.Descriptor instead.
func (*ListArmyPrototypesResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListArmyPrototypesResponse) GetPrototypes() []*ArmyPrototype {
	if x != nil {
		return x.Prototypes
	}
	return nil
}

type GetArmyPrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArmyPrototypeRequest) Reset() {
	*x = GetArmyPrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArmyPrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArmyPrototypeRequest) ProtoMessage() {}

func (x *GetArmyPrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArmyPrototypeRequest.ProtoReflect.Descriptor instead.
func (*GetArmyPrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetArmyPrototypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArmyPrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *ArmyPrototype         `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArmyPrototypeResponse) Reset() {
	*x = GetArmyPrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArmyPrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArmyPrototypeResponse) ProtoMessage() {}

func (x *GetArmyPrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArmyPrototypeResponse.ProtoReflect.Descriptor instead.
func (*GetArmyPrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetArmyPrototypeResponse) GetPrototype() *ArmyPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

// CreateArmyPrototypeRequest carries the prototype to insert. The caller MUST set
// a positive id: prototypes are ordered and each type occupies its own id range,
// so the id is chosen by the caller rather than assigned by the server.
type CreateArmyPrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *ArmyPrototype         `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArmyPrototypeRequest) Reset() {
	*x = CreateArmyPrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArmyPrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArmyPrototypeRequest) ProtoMessage() {}

func (x *CreateArmyPrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArmyPrototypeRequest.ProtoReflect.Descriptor instead.
func (*CreateArmyPrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *CreateArmyPrototypeRequest) GetPrototype() *ArmyPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

type CreateArmyPrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *ArmyPrototype         `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArmyPrototypeResponse) Reset() {
	*x = CreateArmyPrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArmyPrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArmyPrototypeResponse) ProtoMessage() {}

func (x *CreateArmyPrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArmyPrototypeResponse.ProtoReflect.Descriptor instead.
func (*CreateArmyPrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *CreateArmyPrototypeResponse) GetPrototype() *ArmyPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

// UpdateArmyPrototypeRequest overwrites the prototype identified by prototype.id.
type UpdateArmyPrototypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *ArmyPrototype         `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArmyPrototypeRequest) Reset() {
	*x = UpdateArmyPrototypeRequest{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArmyPrototypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArmyPrototypeRequest) ProtoMessage() {}

func (x *UpdateArmyPrototypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArmyPrototypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateArmyPrototypeRequest) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateArmyPrototypeRequest) GetPrototype() *ArmyPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

type UpdateArmyPrototypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prototype     *ArmyPrototype         `protobuf:"bytes,1,opt,name=prototype,proto3" json:"prototype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArmyPrototypeResponse) Reset() {
	*x = UpdateArmyPrototypeResponse{}
	mi := &file_game_grpc_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArmyPrototypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArmyPrototypeResponse) ProtoMessage() {}

func (x *UpdateArmyPrototypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_grpc_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArmyPrototypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateArmyPrototypeResponse) Descriptor() ([]byte, []int) {
	return file_game_grpc_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateArmyPrototypeResponse) GetPrototype() *ArmyPrototype {
	if x != nil {
		return x.Prototype
	}
	return nil
}

var File_game_grpc_v1_admin_proto protoreflect.FileDescriptor

const file_game_grpc_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x18game/grpc/v1/admin.proto\x12\fgame.grpc.v1\"v\n" +
	"\n" +
	"PriceModel\x12\x18\n" +
	"\acredits\x18\x01 \x01(\x03R\acredits\x12\x12\n" +
	"\x04iron\x18\x02 \x01(\x03R\x04iron\x12\x1a\n" +
	"\btitanium\x18\x03 \x01(\x03R\btitanium\x12\x1e\n" +
	"\n" +
	"antimatter\x18\x04 \x01(\x03R\n" +
	"antimatter\"\xc6\x04\n" +
	"\rArmyPrototype\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12)\n" +
	"\x10creation_sources\x18\x04 \x03(\tR\x0fcreationSources\x12\x18\n" +
	"\afaction\x18\x05 \x01(\tR\afaction\x125\n" +
	"\x14unlock_technology_id\x18\x06 \x01(\x03H\x00R\x12unlockTechnologyId\x88\x01\x01\x12+\n" +
	"\x11short_description\x18\a \x01(\tR\x10shortDescription\x12)\n" +
	"\x10full_description\x18\b \x01(\tR\x0ffullDescription\x12.\n" +
	"\x05price\x18\t \x01(\v2\x18.game.grpc.v1.PriceModelR\x05price\x12'\n" +
	"\x0fproduction_time\x18\n" +
	" \x01(\x03R\x0eproductionTime\x12\x14\n" +
	"\x05space\x18\v \x01(\x05R\x05space\x12\x1b\n" +
	"\timage_url\x18\f \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06attack\x18\r \x01(\x05R\x06attack\x12\x18\n" +
	"\adefence\x18\x0e \x01(\x05R\adefence\x12\x1a\n" +
	"\bcapacity\x18\x0f \x01(\x05R\bcapacity\x12\x18\n" +
	"\astealth\x18\x10 \x01(\x05R\astealth\x12\x14\n" +
	"\x05speed\x18\x11 \x01(\x05R\x05speedB\x17\n" +
	"\x15_unlock_technology_id\"\x1b\n" +
	"\x19ListArmyPrototypesRequest\"Y\n" +
	"\x1aListArmyPrototypesResponse\x12;\n" +
	"\n" +
	"prototypes\x18\x01 \x03(\v2\x1b.game.grpc.v1.ArmyPrototypeR\n" +
	"prototypes\")\n" +
	"\x17GetArmyPrototypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"U\n" +
	"\x18GetArmyPrototypeResponse\x129\n" +
	"\tprototype\x18\x01 \x01(\v2\x1b.game.grpc.v1.ArmyPrototypeR\tprototype\"W\n" +
	"\x1aCreateArmyPrototypeRequest\x129\n" +
	"\tprototype\x18\x01 \x01(\v2\x1b.game.grpc.v1.ArmyPrototypeR\tprototype\"X\n" +
	"\x1bCreateArmyPrototypeResponse\x129\n" +
	"\tprototype\x18\x01 \x01(\v2\x1b.game.grpc.v1.ArmyPrototypeR\tprototype\"W\n" +
	"\x1aUpdateArmyPrototypeRequest\x129\n" +
	"\tprototype\x18\x01 \x01(\v2\x1b.game.grpc.v1.ArmyPrototypeR\tprototype\"X\n" +
	"\x1bUpdateArmyPrototypeResponse\x129\n" +
	"\tprototype\x18\x01 \x01(\v2\x1b.game.grpc.v1.ArmyPrototypeR\tprototype2\xba\x03\n" +
	"\x14ArmyPrototypeService\x12g\n" +
	"\x12ListArmyPrototypes\x12'.game.grpc.v1.ListArmyPrototypesRequest\x1a(.game.grpc.v1.ListArmyPrototypesResponse\x12a\n" +
	"\x10GetArmyPrototype\x12%.game.grpc.v1.GetArmyPrototypeRequest\x1a&.game.grpc.v1.GetArmyPrototypeResponse\x12j\n" +
	"\x13CreateArmyPrototype\x12(.game.grpc.v1.CreateArmyPrototypeRequest\x1a).game.grpc.v1.CreateArmyPrototypeResponse\x12j\n" +
	"\x13UpdateArmyPrototype\x12(.game.grpc.v1.UpdateArmyPrototypeRequest\x1a).game.grpc.v1.UpdateArmyPrototypeResponseBKZIgithub.com/artcodefun/heat-expansion-server/contracts/game/grpc/v1;gamev1b\x06proto3"

var (
	file_game_grpc_v1_admin_proto_rawDescOnce sync.Once
	file_game_grpc_v1_admin_proto_rawDescData []byte
)

func file_game_grpc_v1_admin_proto_rawDescGZIP() []byte {
	file_game_grpc_v1_admin_proto_rawDescOnce.Do(func() {
		file_game_grpc_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_grpc_v1_admin_proto_rawDesc), len(file_game_grpc_v1_admin_proto_rawDesc)))
	})
	return file_game_grpc_v1_admin_proto_rawDescData
}

var file_game_grpc_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_game_grpc_v1_admin_proto_goTypes = []any{
	(*PriceModel)(nil),                  // 0: game.grpc.v1.PriceModel
	(*ArmyPrototype)(nil),               // 1: game.grpc.v1.ArmyPrototype
	(*ListArmyPrototypesRequest)(nil),   // 2: game.grpc.v1.ListArmyPrototypesRequest
	(*ListArmyPrototypesResponse)(nil),  // 3: game.grpc.v1.ListArmyPrototypesResponse
	(*GetArmyPrototypeRequest)(nil),     // 4: game.grpc.v1.GetArmyPrototypeRequest
	(*GetArmyPrototypeResponse)(nil),    // 5: game.grpc.v1.GetArmyPrototypeResponse
	(*CreateArmyPrototypeRequest)(nil),  // 6: game.grpc.v1.CreateArmyPrototypeRequest
	(*CreateArmyPrototypeResponse)(nil), // 7: game.grpc.v1.CreateArmyPrototypeResponse
	(*UpdateArmyPrototypeRequest)(nil),  // 8: game.grpc.v1.UpdateArmyPrototypeRequest
	(*UpdateArmyPrototypeResponse)(nil), // 9: game.grpc.v1.UpdateArmyPrototypeResponse
}
var file_game_grpc_v1_admin_proto_depIdxs = []int32{
	0,  // 0: game.grpc.v1.ArmyPrototype.price:type_name -> game.grpc.v1.PriceModel
	1,  // 1: game.grpc.v1.ListArmyPrototypesResponse.prototypes:type_name -> game.grpc.v1.ArmyPrototype
	1,  // 2: game.grpc.v1.GetArmyPrototypeResponse.prototype:type_name -> game.grpc.v1.ArmyPrototype
	1,  // 3: game.grpc.v1.CreateArmyPrototypeRequest.prototype:type_name -> game.grpc.v1.ArmyPrototype
	1,  // 4: game.grpc.v1.CreateArmyPrototypeResponse.prototype:type_name -> game.grpc.v1.ArmyPrototype
	1,  // 5: game.grpc.v1.UpdateArmyPrototypeRequest.prototype:type_name -> game.grpc.v1.ArmyPrototype
	1,  // 6: game.grpc.v1.UpdateArmyPrototypeResponse.prototype:type_name -> game.grpc.v1.ArmyPrototype
	2,  // 7: game.grpc.v1.ArmyPrototypeService.ListArmyPrototypes:input_type -> game.grpc.v1.ListArmyPrototypesRequest
	4,  // 8: game.grpc.v1.ArmyPrototypeService.GetArmyPrototype:input_type -> game.grpc.v1.GetArmyPrototypeRequest
	6,  // 9: game.grpc.v1.ArmyPrototypeService.CreateArmyPrototype:input_type -> game.grpc.v1.CreateArmyPrototypeRequest
	8,  // 10: game.grpc.v1.ArmyPrototypeService.UpdateArmyPrototype:input_type -> game.grpc.v1.UpdateArmyPrototypeRequest
	3,  // 11: game.grpc.v1.ArmyPrototypeService.ListArmyPrototypes:output_type -> game.grpc.v1.ListArmyPrototypesResponse
	5,  // 12: game.grpc.v1.ArmyPrototypeService.GetArmyPrototype:output_type -> game.grpc.v1.GetArmyPrototypeResponse
	7,  // 13: game.grpc.v1.ArmyPrototypeService.CreateArmyPrototype:output_type -> game.grpc.v1.CreateArmyPrototypeResponse
	9,  // 14: game.grpc.v1.ArmyPrototypeService.UpdateArmyPrototype:output_type -> game.grpc.v1.UpdateArmyPrototypeResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_game_grpc_v1_admin_proto_init() }
func file_game_grpc_v1_admin_proto_init() {
	if File_game_grpc_v1_admin_proto != nil {
		return
	}
	file_game_grpc_v1_admin_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_grpc_v1_admin_proto_rawDesc), len(file_game_grpc_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_grpc_v1_admin_proto_goTypes,
		DependencyIndexes: file_game_grpc_v1_admin_proto_depIdxs,
		MessageInfos:      file_game_grpc_v1_admin_proto_msgTypes,
	}.Build()
	File_game_grpc_v1_admin_proto = out.File
	file_game_grpc_v1_admin_proto_goTypes = nil
	file_game_grpc_v1_admin_proto_depIdxs = nil
}
